### ISSUE TITLE
Standardize exceptions thrown from Evaluator.evaluate()

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#141]
---

Author Name: **Evan** (Evan)
Original Redmine Issue: 122335, https://vlab.noaa.gov/redmine/issues/122335
Original Date: 2023-11-07

---

When calling the @Evaluator.evaluate()@ function there was a case where a duplicate field was throwing a @DeclarationException@ instead of being wrapped in an @UserInputException@ and another case where removing the ":" from a yml declaration is returning a @ContainerException@ instead of a @UserInputException@ or @InternalWresException@.

We should strive for a clean API and have a set list of expected exceptions that are returned to facilitate proper handling. The first issue above was remedied, but there are likely other occurrences of mishandled exceptions that are not wrapped properly. Go through the Evaluation pipeline and properly handle/wrap exceptions

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **Evan** (Evan)
Original Date: 2023-11-07T15:57:51Z

---

Declaration causing the ContainerException:

```
label semi
observed: /mnt/wres_share/systests/data/DRRC2QINE.xml
predicted:
  label: HEFS
  sources: /mnt/wres_share/systests/data/drrc2ForecastsOneMonth/
unit: m3/s
lead_times:
  minimum: 0
  maximum: 48
  unit: hours
probability_thresholds:
  values: [0.002, 0.01, 0.1, 0.9, 0.99, 0.998]
  operator: greater equal
metrics:
  - quantile quantile diagram
  - rank histogram
  - relative operating characteristic diagram
  - box plot of errors by forecast value
  - root mean square error
  - sample size
  - mean absolute error
  - box plot of errors by observed value
  - reliability diagram

```
