### ISSUE TITLE
As a user, I don't expect an Internal Server Error when posting a declaration through the API

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#24]
An example declaration is below with paths partially omitted. Specifically, its the `time_zone_offset` causing the problem. If its an integer, the tasker reports an internal server error resulting from validation (I think):

```
Internal Server Error
Unable to validate project configuration due to internal error.
```

Presumably, there are other YAML parameters that can trigger the same error, but I'm not sure which. Hopefully, fixing it for this will fix it for all.  

Hank

(See VLab ticket 126661 for the discovery of the error.)

==========================

```yml
label: BV Streamflow - Hank Test
observed:
  label: OBS Streamflow
  sources:
  - uri: [omitted]/issue92087/inputs/ABRN1_QME.xml
  variable:
    name: QME
  feature_authority: nws lid
  time_scale:
    function: mean
    period: 24
    unit: hours
  type: observations
predicted:
  label: HEFS Streamflow
  sources:
  - uri: [omitted]/issue126661/clone_uppermotribs_hefs_1985
  variable:
    name: SQIN
  time_scale:
    function: mean
    period: 1
    unit: minutes
  type: ensemble forecasts
  time_zone_offset: 0
  unit: CMS
unit: ft3/s
lead_time_pools:
  period: 24
  frequency: 24
  unit: hours
cross_pair: exact
lead_times:
  minimum: 18
  maximum: 720
  unit: hours
season:
  minimum_day: 1
  minimum_month: 1
  maximum_day: 31
  maximum_month: 12
time_scale:
  function: mean
  period: 24
  unit: hours
pair_frequency:
  period: 24
  unit: hours
rescale_lenience: none
features:
- observed: ABRN1
  predicted: ABRN1
probability_thresholds:
- values:
  - 0.01
  - 0.1
  - 0.5
  - 0.9
  - 0.95
  - 0.99
  - 0.995
  - 0.999
  operator: greater
  apply_to: observed
metrics:
- name: brier score
- name: pearson correlation coefficient
- name: bias fraction
- name: continuous ranked probability score
- name: mean absolute error
- name: mean error
- name: sample size
duration_format: hours
decimal_format: '0.000'
output_formats:
- format: csv2
- format: png
  width: 800
  height: 600
  orientation: lead threshold
- format: netcdf2
```
