### ISSUE TITLE
Expose metrics for rabbitMQ broker

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#300]
In order to supply more metrics to our monitoring solution we should expose the metrics for rabbitMQ to our monitoring solution.

The easiest approach would be to expose the default metrics port 15692 to broker docker image
```
    broker:
        hostname: localhost
        ports:
         - "5671:5671"
         - "15671:15671"
         - "15692:15692"

```

We could then add a new entry into the nginx reverse proxy in order to add TLS to this easily.
or just modify the config file https://www.rabbitmq.com/docs/prometheus#tls

Also look into the detailed metrics monitoring
https://hodovi.cc/blog/rabbitmq-per-queue-monitoring/
