### ISSUE TITLE
As a user, I expect feature offsets to be applied when reading data from WRDS

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#316]
See #36. The `offset` feature appears to work fine when using a flat file for the `predicted` data, but does not when using the WRDS RFC forecast service. The simplified declaration I used to test this with flat files is below. The mean errors are around 11 ft for BGDA2. If I swap the `predicted` for WRDS, the mean errors are in excess of 950 ft.

Thanks,

Hank

=======================================================

```yaml
observed:
  label: USGS NWIS Stage Observations
  sources:
  - interface: usgs nwis
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
  variable: '00065'
predicted:
  label: WRDS AHPS API Stage Forecast
  sources:
  - interface: wrds ahps
    uri: 132968_wrds_rfc_forecasts.json.gz
  variable: HG
unit: FT
lead_time_pools:
  period: 6
  unit: hours
lead_times:
  minimum: 0
  maximum: 72
  unit: hours
reference_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
valid_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
features:
- observed: { name: '15478000', offset: -975 }
  predicted: BGDA2
- observed: '15056500'
  predicted: CKTA2
metrics:
- mean error
- sample size
- mean absolute error
minimum_sample_size: 1
duration_format: hours
output_formats:
- format: png
  width: 960
  height: 720
```
