### ISSUE TITLE
As a user, when I include both features and a feature_service group in an evaluation for only bias fraction and again for just POD, I expect outputs for the same features and thresholds

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#319]
See VLab User Support ticket #134706. The name of this ticket is nearly identical to that one, but feel free to rename it later if there is a better, more searchable name to use.

For a given evaluation that includes both `features` and a `feature_service` `group`, with the declaration in that ticket (comment 1), if I run it with POD and FAR metrics, I get results for both sets of features, but, if I specify bias fraction or sample size, even if POD and FAR are still included, I only get results for the `features`, not the `group`. A log message indicates that the features in the `group` were dropped due to lack of thresholds; for example:

> 2024-09-13T18:46:34.621+0000 WARN DeclarationUtilities Discovered 11 feature(s) for which thresholds were not available. These features have been removed from the evaluation. The features are: [{"left":{"name":"04195500"},"right":{"name":"WDVO1"}}, {"left":{"name":"04199000"},"right":{"name":"MILO1"}}, {"left":{"name":"04208000"},"right":{"name":"INDO1"}}, {"left":{"name":"04206000"},"right":{"name":"OLPO1"}}, {"left":{"name":"04197137"},"right":{"name":"TFFO1"}}, {"left":{"name":"04196500"},"right":{"name":"UPPO1"}}, {"left":{"name":"04209000"},"right":{"name":"WBYO1"}}, {"left":{"name":"04200500"},"right":{"name":"ELRO1"}}, {"left":{"name":"04198000"},"right":{"name":"FFMO1"}}, {"left":{"name":"04199500"},"right":{"name":"VERO1"}}, {"left":{"name":"04212100"},"right":{"name":"PNVO1"}}].

That log message is not output for the POD/FAR only run.  

I'll upload the data needed to reproduce and the declaration in comment one. Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
A declaration based on the original declaration that reproduces the issue with a single `features` entry for MEDP1 is provided below. Links to thresholds and RFC forecast data to support that declaration are then provided. Thanks,

Hank

==========

```yaml
label: CLE - REPRODUCE
observed:
  label: USGS NWIS Stage Observations
  sources:
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
    interface: usgs nwis
  variable: "00065" 
  type: observations
predicted:
  label: WRDS AHPS API Stage Forecasts
  sources:
    uri: https://[WRDS]/api/rfc_forecast/v2.0/forecast/stage
    interface: wrds ahps
  variable:
    name: HG
    label: stage
    aliases:
      - HP
      - HT
  type: single valued forecasts
features:
  - {observed: "03023100", predicted: MEDP1}
#  - {observed: "03094000", predicted: LEAO1}
#  - {observed: "411402080492400", predicted: WRNO1}
#  - {observed: "03098600", predicted: YGWO1}
#  - {observed: "03117000", predicted: MLNO1}
#  - {observed: "03118500", predicted: NHSO1}
#  - {observed: "03136500", predicted: MVEO1}
#  - {observed: "03139000", predicted: KILO1}
#  - {observed: "03217500", predicted: LARO1}
#  - {observed: "03219500", predicted: PRGO1}
#  - {observed: "04189000", predicted: FDYO1}
#  - {observed: "04193500", predicted: WTVO1}
feature_service:
  uri: https://[WRDS]/api/location/v3.0/metadata
  group: tag
  value: OHRFC_SGTL
unit: FT
reference_dates:
  minimum: 2024-09-01T00:00:00Z
  maximum: 2024-09-13T00:00:00Z
valid_dates:
  minimum: 2024-09-01T00:00:00Z
  maximum: 2024-09-13T00:00:00Z
lead_times:
  minimum: 0
  maximum: 120
  unit: hours
threshold_sources:
  uri: https://[WRDS]/api/location/v3.0/nws_threshold/
  operator: greater equal
  feature_name_from: predicted
  parameter: stage
  provider: NWS-NRLDB
metrics:
  - probability of detection
  - false alarm ratio
duration_format: days
output_formats:
  - csv2
  - png
  - pairs
 ```

[134706_thresholds_MEDP1.json](https://github.com/user-attachments/files/17061661/134706_thresholds_MEDP1.json)
[134706_thresholds_OHRFC_SGTL.json](https://github.com/user-attachments/files/17061663/134706_thresholds_OHRFC_SGTL.json)
[134706_feature_group_tag_OHRFC_SGTL_stage.json](https://github.com/user-attachments/files/17061667/134706_feature_group_tag_OHRFC_SGTL_stage.json)
[134706_rfc_forecast_medp1_stage.json](https://github.com/user-attachments/files/17061668/134706_rfc_forecast_medp1_stage.json)
