### ISSUE TITLE
As a user, I would like apply a feature-specific adjustment to data and threshold values in order to account for datum differences

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#36]
There may be other contexts in which this is useful, as well. This is from a WRES User Support VLab ticket #132398. The problem was that USGS NWIS was providing data relative to MSL, while the WRDS AHPS forecasts are providing simple river levels. Though the WRDS location service includes zero_datum, it is not being applied in the WRDS RFC forecast service. Its unclear if the WRDS should apply that zero_datum by default or via flag. This ticket, however, is for a work-around that would allow for the offset to be declared by the user on a feature-by-feature basis, and then applied to ingested data for one side of the evaluation as well as thresholds when appropriate (as would be the case here if WRDS thresholds were used).  

Thanks,

Hank

**Comment by james-d-brown** [comment]
I expect the cleanest way to include this is inband to the declaration of features. For example, you could optionally declare an `observed_datum` (and/or `predicted_datum` and `baseline_datum`). When non-zero, this would be subtracted from the oriented time-series event values.

```
unit: ft
features:
  - {observed: LGNN5, predicted: LGNN5, baseline: LGNN5, observed_datum: 2.3}
```

By definition, a datum is only relevant when adjusting measurements in the evaluation units, so the unit is the evaluation `unit`.

This would be the manual approach. The preferred way would be to use information inband to the data sources, such as WRDS responses.

For thresholds, I don't think there is any need for manual declaration because, if you are declaring the threshold inband, you can declare it with the correct datum offset. If it's coming from a file source or service, it may be necessary to add a `datum` to the `threshold_sources`, which are declared in threshold `unit`, defaulting back to the evaluation `unit` when undeclared.

```
threshold_sources:
  uri: foo_thresholds.csv
  parameter: stage
  provider: NWS-NRLDB
  rating_provider: NRLDB
  missing_value: -999.0
  feature_name_from: predicted
  datum: 0.70104
  unit: m
``` 

Again, though, the preferred approach would be to use information inband to the threshold sources, such as WRDS responses.

**Comment by james-d-brown** [comment]
Actually, the language we want to use is probably `vertical_offset`, which is a numeric offset to apply to the elevation registered in a given datum, rather than `datum`, which is more like a reference name or code to the vertical datum used. In this context, we don't actually care what the datum represents, simply that the elevations needs to be adjusted by a fixed value or `vertical_offset`.

Also, while we try not to be too hierarchical in our declaration language, it is more extensible and cleaner to attach this attribute to each feature/single separately. Indeed, we already allow a `wkt` to be declared separately from a `name`. In other words, this:

```
features:
  - { observed: { name: LGNN5, vertical_offset: 2.3 }, predicted: LGNN5, baseline: LGNN5 }
```

Or, equivalently, in the block style:

```
features:
  - observed:
      name: LGNN5
      vertical_offset: 2.3
    predicted: LGNN5
    baseline: LGNN5
```

**Comment by james-d-brown** [comment]
Assigning, starting. Estimating 16 bananas. Whether this makes it into 6.25. idk. Even if we aren't ready to deploy 6.25, I may hold off merging this into main because 6.25 is already too big.

**Comment by james-d-brown** [comment]
> Or, equivalently, in the block style:
> 
> ```
> features:
>   - observed:
>       name: LGNN5
>       vertical_offset: 2.3
>     predicted: LGNN5
>     baseline: LGNN5
> ```

On the nomenclature, we could also make this more general and simply call it an `offset`, to be understood as a value to add (or subtract?) to (from) each time-series event value on the designated dataset orientation. That way, it serves the purpose of a datum offset, but could be used (or more easily understood as being useful) in other contexts too.

**Comment by james-d-brown** [comment]
**Hank**, when you get a minute, could you provide a self-contained example for vlab ticket 132398 for BGDA2? 

The declaration is there, it just needs the wrds time-series, threshold and location responses. Some of that may be in the ticket, such as the wrds time-series response, although that may be a minimal dataset rather than the actual dataset the user deployed (preferred).

TIA.

**Comment by HankHerr-NOAA** [comment]
James:

I'll do my best to get that example to you today, but its a pretty full day. I may not be able to get you the example until Monday.  

Thanks,

Hank

**Comment by james-d-brown** [comment]
Thanks!

**Comment by HankHerr-NOAA** [comment]
VLab ticket #132398 has the needed data to reproduce the evaluation with declaration shared in that ticket. If you would like for me to share that data in this ticket, let me know.

Hank

**Comment by james-d-brown** [comment]
Thanks! Yeah, would make sense to share here too, I think.

**Comment by james-d-brown** [comment]
> For thresholds, I don't think there is any need for manual declaration because, if you are declaring the threshold inband, you can declare it with the correct datum offset. If it's coming from a file source or service, it may be necessary to add a `datum` to the `threshold_sources`, which are declared in threshold `unit`, defaulting back to the evaluation `unit` when undeclared.
> 
> ```
> threshold_sources:
>   uri: foo_thresholds.csv
>   parameter: stage
>   provider: NWS-NRLDB
>   rating_provider: NRLDB
>   missing_value: -999.0
>   feature_name_from: predicted
>   datum: 0.70104
>   unit: m
> ```

Actually, this wouldn't work because it would need to be feature-specific, as with the time-series data.

However, I don't think it makes sense to provide a clunky option to declare a feature-specific offset for thresholds or even to add a clunky option to clarify whether the offsets declared within the scope of `features` also apply to thresholds. Afterall, the thresholds could have a different datum offset than each side of data, which could in turn all differ, in principle. 

In this situation (in all situations), it makes sense to convert the time-series data to the threshold datum. In other words, a user declares the offsets w/r to each side of time-series data and not for thresholds, separately.

Naturally, we should eventually support an automatic offset calculation for the data served from the WRDS threshold service, but that is a future activity.

**Comment by HankHerr-NOAA** [comment]
Declaration is below, as well as the thresholds. RFC forecast data is attached. It should span the desired period plus a few extra hours on each side.

Hank

======================== Declaration

```yml
label: stage test bgda2-ckta2
observed:
  label: USGS NWIS Stage Observations
  sources:
  - interface: usgs nwis
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
  variable:
    name: '00065'
  feature_authority: usgs site code
  type: observations
predicted:
  label: WRDS AHPS API Stage Forecast
  sources:
  - interface: wrds ahps
    uri: https://nwcal-wrds.[domain]/api/rfc_forecast/v2.0/forecast/stage
  variable:
    name: HG
  feature_authority: nws lid
  type: single valued forecasts
unit: FT
lead_time_pools:
  period: 6
  frequency: 6
  unit: hours
lead_times:
  minimum: 0
  maximum: 72
  unit: hours
reference_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
valid_dates:
  minimum: '2023-05-01T12:00:00Z'
  maximum: '2023-11-01T00:00:00Z'
features:
- observed: '15478000'
  predicted: BGDA2
- observed: '15056500'
  predicted: CKTA2
feature_service:
  uri: https://nwcal-wrds.[domain]/api/location/v3.0/metadata
metrics:
- name: sample size
- name: mean absolute error
- name: false alarm ratio
threshold_sources:
- uri: https://nwcal-wrds.[domain]/api/location/v3.0/nws_threshold/
  operator: greater equal
  apply_to: observed
  type: value
  parameter: stage
  provider: NWS-NRLDB
  rating_provider: NRLDB
  feature_name_from: observed
minimum_sample_size: 1
summary_statistics:
  statistics:
  - mean
  dimensions:
  - features
duration_format: days
output_formats:
- format: png
  width: 960
  height: 720
  orientation: lead threshold
```

======================== Thresholds

```json
{
    "_metrics": {
        "threshold_count": 3,
        "total_request_time": 0.10360908508300781
    },
    "_warnings": [],
    "_documentation": {
        "swagger URL": "nwcal-wrds.[domain]/docs/location/v3.0/swagger/" 
    },
    "deployment": {
        "api_url": "https://nwcal-wrds.[domain]/api/location/v3.0/nws_threshold/nws_lid/CKTA2,BGDA2/",
        "stack": "prod",
        "version": "v3.6.0",
        "api_caller": "None" 
    },
    "Non-urgent_issue_reporting_link": "https://vlab.noaa.gov/redmine/projects/wrds-user-support/issues/new?issue[category_id]=2830",
    "data_sources": {
        "metadata_sources": [
            "NWS data: NRLDB - Last updated: 2024-08-13 22:54:57 UTC",
            "USGS data: USGS NWIS - Last updated: 2024-08-13 22:17:52 UTC" 
        ],
        "crosswalk_datasets": {
            "location_nwm_crosswalk_dataset": {
                "location_nwm_crosswalk_dataset_id": "3.0",
                "name": "Location NWM Crosswalk v3.0",
                "description": "Created 20240328. Authoritative 3.0 dataset mapping Locations to NWM Reaches.  Source:\n1) NWM Routelink File v3.0\n2) NHDPlus v2.1+\n3) GID" 
            },
            "nws_usgs_crosswalk_dataset": {
                "nws_usgs_crosswalk_dataset_id": "3.0",
                "name": "NWS Station to USGS Gages 3.0",
                "description": "Created 20240328.  Authoritative 3.0 dataset mapping NWS Stations to USGS Gage.  Source:\n1) AHPS CMS Report\n2) HADS dataset\n3) GID" 
            }
        }
    },
    "value_set": [
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "CKTA2",
                "usgs_site_code": "15056500",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 126.0,
                "action": 125.5,
                "flood": 126.0,
                "minor": 126.0,
                "moderate": 129.0,
                "major": 130.5,
                "record": 128.18
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": 16700.0
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 11402.7,
                "action": 10396.2,
                "flood": 11402.7,
                "minor": 11402.7,
                "moderate": 18758.6,
                "major": 22506.5,
                "record": 16592.21,
                "rating_curve": {
                    "location_id": "CKTA2",
                    "id_type": "NWS Station",
                    "source": "NRLDB",
                    "description": "National Weather Service - National River Location Database",
                    "interpolation_method": null,
                    "interpolation_description": null
                }
            }
        },
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "CKTA2",
                "usgs_site_code": "15056500",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 126.0,
                "action": 125.5,
                "flood": 126.0,
                "minor": 126.0,
                "moderate": 129.0,
                "major": 130.5,
                "record": 128.18
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": 16700.0
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 12328.7,
                "action": 11301.0,
                "flood": 12328.7,
                "minor": 12328.7,
                "moderate": 18944.9,
                "major": 22506.5,
                "record": 17062.57,
                "rating_curve": {
                    "location_id": "15056500",
                    "id_type": "USGS Gage",
                    "source": "USGS Rating Depot",
                    "description": "The EXSA rating curves provided by USGS",
                    "interpolation_method": "logarithmic",
                    "interpolation_description": "logarithmic" 
                }
            }
        },
        {
            "metadata": {
                "data_type": "NWS Stream Thresholds",
                "nws_lid": "BGDA2",
                "usgs_site_code": "15478000",
                "nwm_feature_id": null,
                "threshold_type": "all (stage,flow)",
                "stage_units": "FT",
                "flow_units": "CFS",
                "calc_flow_units": "CFS",
                "threshold_source": "NWS-NRLDB",
                "threshold_source_description": "National Weather Service - National River Location Database" 
            },
            "stage_values": {
                "low": 0.0,
                "bankfull": 22.0,
                "action": 22.0,
                "flood": 23.0,
                "minor": 23.0,
                "moderate": 25.0,
                "major": 27.0,
                "record": null
            },
            "flow_values": {
                "low": 0.0,
                "bankfull": null,
                "action": null,
                "flood": null,
                "minor": null,
                "moderate": null,
                "major": null,
                "record": null
            },
            "calc_flow_values": {
                "low": null,
                "bankfull": 63375.7,
                "action": 63375.7,
                "flood": 71816.9,
                "minor": 71816.9,
                "moderate": 90530.4,
                "major": 111737.9,
                "record": null,
                "rating_curve": {
                    "location_id": "BGDA2",
                    "id_type": "NWS Station",
                    "source": "NRLDB",
                    "description": "National Weather Service - National River Location Database",
                    "interpolation_method": null,
                    "interpolation_description": null
                }
            }
        }
    ]
}
[132968_wrds_rfc_forecasts.json.gz](https://github.com/user-attachments/files/16627115/132968_wrds_rfc_forecasts.json.gz)

```

**Comment by HankHerr-NOAA** [comment]
Need to fix that comment. Something didn't work right.

**Comment by HankHerr-NOAA** [comment]
Oh, I see.

James: Please ignore the last line of the threshold JSON. It appears my attempt to attach a file somehow resulted in that weird text. 

Hank

**Comment by james-d-brown** [comment]
Seems to be working locally, both for features and feature groups. For example, declaration like this produces the expected offset in relevant statistics (e.g., mean error):

```
features:
  - { observed: { name: DOSC1, offset: 100 }, predicted: DOSC1 }
```

As does this, which is equivalent declaration for a singleton feature group:

```
feature_groups:
  - name: DOSC1
    features:
      - { observed: { name: DOSC1, offset: 100 }, predicted: DOSC1 }
```
