### ISSUE TITLE
As a, when running in in-memory mode, I want valid dates pools to account for rescaling period in order to ensure I get all expected, rescaled pairs in the pools

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#369]
#357 handled the database version of this ticket. This is for in-memory. I'll share the smallest declaration that I used to reproduce the problem in the first comment. The data backing the evaluation was shared in #357. 

The problem is that the `valid_dates` are declared as (3/18 0Z  - 3/21 0Z]. Given the data involved, that should yield pairs for 3/18, 3/19, and 3/20 6Z. However, the 3/18 6Z value is not produced, because it only finds one value (at 3/18 6Z) to support the upscaling due to the `valid_dates` pool not being adjusted to account for the rescaling period. 

Again, details are in #357. Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
The declaration is below. With this declaration, when run using a database, I get pairs for 3/18 6Z. When run in in-memory mode, I do not.

Hank

```yaml
label: BV Streamflow
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
predicted:
  label: HEFS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_Streamflow_HEFS_Baseline_Validation.tgz
  variable: SQIN
  type: ensemble forecasts
features:
  - {observed: ABRN1, predicted: ABRN1} 
unit: ft3/s
valid_dates:
  minimum: 1995-03-18T00:00:00Z
  maximum: 1995-03-21T00:00:00Z 

time_scale:
  function: mean
  period: 24
  unit: hours

metrics:
  - mean error
  - pearson correlation coefficient
  - sample size
  - root mean square error
  - mean absolute error
output_formats:
  - csv2
  - format: png
    orientation: lead threshold
  - pairs
```
