### ISSUE TITLE
As a user, I expect the declared reference_dates to be reflected in the evaluation.csv output

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#385]
As part of testing #382, I posted the declaration below and examined the `evaluation.csv` using Excel. This is what I saw in the columns for the issued dates:

![Image](https://github.com/user-attachments/assets/9a937ef8-b9c5-4f97-9564-236bb2bb1f27)

The two columns are unbounded instead of reflecting the declared `reference_dates`.

The observation data should already be available, but I can provide it again if needed. Obtaining the WRDS data is a bit more challenging; let me see if I can get that done before I leave today.

Thanks,

Hank

===================================

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: AHPS Streamflow Forecast
  sources:
    - uri: https://WRDS/api/rfc_forecast/v2.0/forecast/streamflow
      interface: wrds ahps
  variable: QR
  type: single valued forecasts

features:
 - {observed: 'ABRN1' , predicted: 'ABRN1' }

time_scale:
  function: mean
  period: 24
  unit: hours

reference_dates:
  minimum: 2000-08-07T23:00:00Z
  maximum: 2015-08-08T23:00:00Z

event_detection: observed

metrics:
  - time to peak error
  - sample size
  - pearson correlation coefficient

output_formats:
  - csv2
  - png
```
