### ISSUE TITLE
As a user, I want to be able to declare use of the ensemble forecasts to compute time to peak error when I have also declared an ensemble average

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#387]
See #382. Using an `ensemble forecasts` `predicted`, this declaration will fail validation:

```yaml
ensemble_average: mean
metrics:
  - pearson correlation coefficient
  - sample size
  - name: time to peak error
    # ensemble_average: mean
    summary_statistics:
    - median
    - minimum
    - maximum
    - mean
```

The `ensemble_average` setting will turn the ensemble forecast into a single valued forecast, so computing the time to peak error should be possible. However, it fails validation:

> The declared or inferred data 'type' for the 'predicted' dataset is ensemble forecasts, but the following metrics are not currently supported for this data 'type': [TIME TO PEAK ERROR]. Please remove these metrics or change the data 'type'.

The check above needs to consider the `ensemble_average` setting, but does not.  Thanks,

Hank

**Comment by james-d-brown** [comment]
Reproduced:

```
Caused by: wres.config.yaml.DeclarationException: Encountered 1 error(s) in the declared evaluation, which must be fixed:
    - The declared or inferred data 'type' for the 'predicted' dataset is ensemble forecasts, but the following metrics are not currently supported for this data 'type': [TIME TO PEAK ERROR]. Please remove these metrics or change the data 'type'.
	at wres.config.yaml.DeclarationValidator.notify(DeclarationValidator.java:497)
	at wres.config.yaml.DeclarationValidator.validatePostDataIngest(DeclarationValidator.java:450)
	at wres.io.project.ProjectUtilities.validate(ProjectUtilities.java:995)
	at wres.io.project.InMemoryProject.<init>(InMemoryProject.java:163)
	at wres.io.project.Projects.getProject(Projects.java:83)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:650)
	at wres.pipeline.Evaluator.evaluate(Evaluator.java:378)
	... 7 common frames omitted
```

**Comment by james-d-brown** [comment]
Ah, this isn't actually a bug because the `ensemble_average` isn't an instruction to transform the data to single-valued predictions, rather it is an explicit designation of the average to use when that activity is performed. Currently, that activity is only performed for the traditional single-valued measures, not the time-series measures.

In short, this is a feature enhancement, not a bug. I can look at the enhancement, though, to see whether it is straightforward to implement.

**Comment by james-d-brown** [comment]
Looks to be fairly straightforward, doing it. Will need to adjust the csv2 output to qualify the averaging mode for these time-series metrics.

**Comment by james-d-brown** [comment]
Pushed the changes and unit tests.

**Comment by james-d-brown** [comment]
Scheduled for UAT.

**Comment by HankHerr-NOAA** [comment]
UATing... I'm going to find the #382 HEFS ensemble evaluation that I ran when I posted this ticket,

Hank

**Comment by HankHerr-NOAA** [comment]
I found the declaration shown below. The evaluation is currently running,

Hank

==========

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: HEFS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_Streamflow_HEFS_Baseline_Validation.tgz
  variable: SQIN
  type: ensemble forecasts
  time_scale:
    function: mean
    period: 60
    unit: seconds

features:
 - {observed: 'ABRN1' , predicted: 'ABRN1' }

time_scale:
  function: mean
  period: 24
  unit: hours

event_detection: observed
ensemble_average: mean
metrics:
  - pearson correlation coefficient
  - sample size
  - name: time to peak error
    summary_statistics:
    - median
    - minimum
    - maximum
    - mean


output_formats:
  - csv2
  - png
```
