### ISSUE TITLE
As a user, I don't expect to see an UNKNOWN domain axis title when using event detection

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#390]
The specific situation is that `observed` are NWM v3.0 retrosim, `predicted` are WRDS RFC forecasts, and `covariates` list one covariate for HEFS observations. The declaration is below. This resulted in the image shown in the comment,

https://github.com/NOAA-OWP/wres/issues/382#issuecomment-2613126093

The domain axis label is, "UNKNOWN [UTC]". In my opinion, that is sort of equivalent to an NPE: it should never happen. Hence, this ticket. If I'm wrong, and unknown is reasonable for this axis label, please explain. 

All data for this evaluation is in the `GitHub_382` folder within `WRES Redmine Ticket Large Data Sets' on Google Drive. The retrosim data is a bit large, but I can attach the other two files to this ticket if desired. 

Thanks,

Hank

==========

```yaml
label: Testing Event Based
observed:
  label: "19161749 RetroSim CSVs"
  sources:
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/OAX/19161749_nwm_3_0_retro_wres.csv.gz
  variable: streamflow
  feature_authority: nwm feature id
  type: simulations

predicted:
  label: AHPS Streamflow Forecast
  sources:
    - uri: https://WRDS/api/rfc_forecast/v2.0/forecast/streamflow
      interface: wrds ahps
  variable: QR
  type: single valued forecasts

covariates:
  - label: OBS streamflow covariate
    sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
    variable: QME
    feature_authority: nws lid
    type: observations
    time_scale:
      function: mean
      period: 24
      unit: hours

features:
 - {observed: '19161749' , predicted: 'ABRN1' }
 - 
time_scale:
  function: mean
  period: 24
  unit: hours

reference_dates:
  minimum: 2000-08-07T23:00:00Z
  maximum: 2015-08-08T23:00:00Z

event_detection: covariates

metrics:
  - pearson correlation coefficient
  - sample size
  - name: time to peak error
    summary_statistics:
    - median
    - minimum
    - maximum
    - mean

output_formats:
  - csv2
  - png
```
