### ISSUE TITLE
As a user, I want to see sampling uncertainty properly reflected in time to peak error diagrams

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#399]
James: Please adjust the title and description accordingly.

As reported in #382, I added sampling uncertainty to an event detection evaluation wherein the time to peak error was computed. As a user, I expect that, when I ask for sampling uncertainty in an evaluation that includes time to peak error, I'll see a plot of time to peak errors that includes whiskers. Either that, or, if the WRES does not support sampling uncertainty whiskers for the plot, then the plot will be identical to the results for an equivalent evaluation with no sampling uncertainty.  

That was not the case here: the plot of time to peak error against earliest valid time did not include whiskers and was not the same. Example plots are in [this comment](https://github.com/NOAA-OWP/wres/issues/382#issuecomment-2634658457). Note that James responded in three comments that followed that comment indicating that this would be another ticket and not necessarily related to event detection. 

The declaration to use to reproduce this results is below. Just comment out the `sampling_uncertainty` component to get a "before" result. As always, the data backing this evaluation is in the VLab Redmine Large Data Sets Google Drive folder.

If any more information is needed, let me know. Thanks,

Hank

==========

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: "19161749 RetroSim CSVs"
  sources:
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/OAX/19161749_nwm_3_0_retro_wres.csv.gz
  variable: streamflow
  feature_authority: nwm feature id
  type: simulations

features:
  - {observed: ABRN1, predicted: '19161749'}

time_scale:
  function: maximum
  #  period: 24
  period: 168
  unit: hours

event_detection: observed

sampling_uncertainty:
  sample_size: 1000
  quantiles: [0.05,0.95]

metrics:
  - time to peak error
  - sample size
  - pearson correlation coefficient

output_formats:
  - csv2
  - png
```
