### ISSUE TITLE
As a user, if I run an evaluation with three features, I expect the events identified for one of those features to be the same as if I ran that feature alone

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#400]
This comes from [this comment](https://github.com/NOAA-OWP/wres/issues/382#issuecomment-2636863066) in #382.

The declaration is below. If I only run ABRN1, I get this Pearson correlation plot for ABRN1:

![Image](https://github.com/user-attachments/assets/82545656-af89-4ba9-abd3-2d6bd52fca70)

If I run all three features in the declaration, I get this Pearson correlation plot for ABRN1:

![Image](https://github.com/user-attachments/assets/8e67d0cc-551a-4167-9a33-fde039e397b8)

There are many more identified events for ABRN1. When I looked through the evaluation CSV using an `awk` command in the comment, above, the events for all three features are close to identical (only 2 or 3 differ, perhaps due to data availability).  Bottom line, I think it may be combining events across features.

This ticket can be resolved once I am able to get the same features for ABRN1 whether run alone or with other features. Thanks,

Hank

=================

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: 
  - /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  - /home/ISED/wres/wresTestData/issue92087/inputs/BKBN6_QME.xml
  - /home/ISED/wres/wresTestData/issue92087/inputs/WTFN6_QME.xml 
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: "19161749 RetroSim CSVs"
  sources: 
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/OAX/19161749_nwm_3_0_retro_wres.csv.gz
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/ALY/3246744_nwm_3_0_retro_wres.csv.gz
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/ALY/22290557_nwm_3_0_retro_wres.csv.gz
  variable: streamflow
  feature_authority: nwm feature id
  type: simulations

features:
  - {observed: ABRN1, predicted: '19161749'}
  - {observed: BKBN6, predicted: '3246744'}
  - {observed: WTFN6, predicted: '22290557'}

time_scale:
  function: maximum
  #  period: 24
  period: 168
  unit: hours

event_detection: observed
sampling_uncertainty:
  sample_size: 1000
  quantiles: [0.05,0.95]

metrics:
  - time to peak error
  - sample size
  - pearson correlation coefficient

output_formats:
  - csv2
  - png
```
