### ISSUE TITLE
As a user, I want to calculate statistics between two thresholds

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#402]
Given an evaluation problem that involves thresholds
When I want to calculate continuous or categorical statistics for values that fall between two thresholds, repeated for up to M pairs of thresholds
Then I should be able to declare this evaluation
So that I can address more real-world evaluation problems using WRES

( Reported/requested by Josh Walston of APRFC. )

**Comment by james-d-brown** [comment]
Finally looking at this one.

**Comment by james-d-brown** [comment]
Good progress with the declaration aspects, just adding unit tests for that part.

**Comment by james-d-brown** [comment]
Basically working from a declaration POV, albeit with limited (system-level) testing. Moving on to make it work for WRDS thresholds.

**Comment by james-d-brown** [comment]
Appears to be working for WRDS thresholds too, although more integration/system testing is needed.

**Comment by james-d-brown** [comment]
Working on the CSV thresholds.

**Comment by james-d-brown** [comment]
Ready for UAT. Will require some minor updates to the wiki at deployment time.

**Comment by HankHerr-NOAA** [comment]
I'm going to delay testing until Monday. I've been engrossed in HEFS CBPR coding and would rather not try to split my attention at the end of the day. I'll block of time on Monday morning to start this testing.

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Testing this. I'm going to start with establishing some basic declarations that use thresholds and establish what to expect without using `between`.

Hank

**Comment by HankHerr-NOAA** [comment]
I started with a test I run on staging with WRDS thresholds added and the evaluation period extended to over 20 years. I think ran using the typical `greater` operator and again with `between`. 

First thing I noticed was that `NRLDB action` was equal to `NRLDB bankfull`, so, while both showed up in the `greater` run, only `NRLDB action` showed up in the `between` run.  That makes sense to me: it would be confusing to see 0 sample sizes for the `between` so probably best to just display the results for one of the two. However, in searching the stdout logging, I don't see any mention of "bankfull", so I assume no info or warning is displayed explaining what happened to the threshold. **Would it be possible to get a warning explaining that "NRLDB bankfull" is going to be ignored because it equals "NRLDB action"?**

Next, I made sure I was looking at the same lead time pool and highlighted the columns that provided the sample sizes for the `between` results:

6385
92
8
6
3
6

I then looked that threshold definition for each `between` result, mapped them to the corresponding rows in the `greater` results, and extracted the sample sizes:

6500
115
23
15
9
6

The math works: 6500 - 115 = 6385; 115 - 23 = 92; 23 - 15 = 8; 15 - 9 = 6; 9 - 6 = 3; and, finally, the last left over 6 are all in the last `between` result which was for, "> NRLDB moderate & <= major".  

This all looks good to me. I'm now going to run through other evaluations, including something that uses a CSV file, something that uses declaration defined probability thresholds, and something that uses feature specific, in-declaration thresholds.  I just have to find good examples of each to use.

Stepping away for a few minutes, first,

Hank

**Comment by james-d-brown** [comment]
https://github.com/NOAA-OWP/wres/wiki/Declaration-Language#81-what-types-of-thresholds-are-supported-and-how-do-i-declare-them

**Comment by HankHerr-NOAA** [comment]
Back to UAT...

**James: Does the WRES support feature-specific thresholds defined in the declaration?**

I know it supports it through WRDS and CSV, but am struggling to understand how to do so via the schema.  

I do see where metrics can have their own thresholds. I may try that with sample size to see what happens.

Hank

**Comment by HankHerr-NOAA** [comment]
Thresholds by metric gave me expected results using `probability_thresholds`. I declared `sample_size` to use 25%, 50%, 75%, and 99%, and saw reported sample sizes overing around 2500 (with the last interval ending at 99% having just a bit fewer than the others). 

Hnak

**Comment by HankHerr-NOAA** [comment]
For the multi-feature test, I'm going to start with a two feature test using FROV2 and WALN6. I already have a CSV prepared to support WALN6, as well, so I'll use that as a basis.

Hank

**Comment by james-d-brown** [comment]
I posted the link above. Again here:

https://github.com/NOAA-OWP/wres/wiki/Declaration-Language#81-what-types-of-thresholds-are-supported-and-how-do-i-declare-them

This is what you mean, right?

```
observed: some_observations.csv
predicted: some_forecasts.csv
unit: m
thresholds:
  name: MAJOR FLOOD
  values: 
    - { value: 23.0, feature: DRRC2 }
    - { value: 27.0, feature: DOLC2 }
  operator: greater equal
  apply_to: predicted
  unit: ft
```

**Comment by HankHerr-NOAA** [comment]
Yeah, that's it. Sorry I was being dense. :)

It should be easy enough to test that to see if it matches what I get with a CSV run.  Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
See my comment above. Apparently, if you forget to refresh a window before commenting, its possible to insert a comment now into the middle of a conversation. I didn't expect that.  Anyway, I have what I need to test the features-specific thresholds declared in the YAML.  Thanks!

Hank

**Comment by HankHerr-NOAA** [comment]
James:

Do you have a convenient `sort` command on hand for sorting evaluation output CSVs by feature and then pool, so that I can compare two of them side by side? I know we have one for pairs somewhere.

Thanks,

Hank

**Comment by james-d-brown** [comment]
Sorting by `POOL NUMBER` and `STATISTIC GROUP NUMBER` should be sufficient.

Like this: `(head -n 1 evaluation.csv && tail -n +2 evaluation.csv | sort -t, -k5n,5 -k53n,53 ) > sorted_evaluation.csv`

**Comment by HankHerr-NOAA** [comment]
Got it. Thanks!

For the in-YAML declaration of the thresholds, I'm assuming I'm not declaring it correctly. I'm trying to reproduce results I saw using WRDS thresholds. To do that, I declared the following (just showing the first three declared thresholds):

```yaml
thresholds:
- name: low
  values:
#    - { value: NaN, feature: FROV2 }
    - { value: 0.0, feature: WALN6 }
  operator: between
  apply_to: observed
  feature_name_from: predicted
- name: NRLDB low
  values:
    - { value: 71, feature: FROV2 }
#    - { value: NaN, feature: WALN6 }
  operator: between
  apply_to: observed
  feature_name_from: predicted
- name: NRDB action
  values:
    - { value: 12989, feature: FROV2 }
    - { value: 2709, feature: WALN6 }
  operator: between
  apply_to: observed
  feature_name_from: predicted
- name: NRLDB bankfull
  values:
    - { value: 12989, feature: FROV2 }
    - { value: 5233, feature: WALN6 }
  operator: between
  apply_to: observed
  feature_name_from: predicted
...
```

With that approach, the thresholds are treated independently, which is not surprising given each `thresholds` array item has its own `operator`.  So, for example, I saw results for FROV2 and `NRLDB low`, where the legend says the interval is `(71, infinity)`.

So the WRES is unwilling to connect the multiple thresholds defined using `between`. Is it possible to define those thresholds all in one list of `values`? Perhaps multiple entries for `FROV2`? (From the schema, it appears that each item in `values` must be a single number.)

Using your `sort` command to compare the results of an earlier test,

Hank

**Comment by james-d-brown** [comment]
Yes, you need to model this a little differently. For example:

```
thresholds:
- name: NRDB action/bankfull
  values:
    - { value: 12989, feature: FROV2 }
    - { value: 12989, feature: FROV2 }
    - { value: 2709, feature: WALN6 }
    - { value: 5233, feature: WALN6 }
  operator: between
  apply_to: observed
  feature_name_from: predicted
```

In this case, it doesn't make a ton of sense for FROV2. But the idea is that you are conceptually modelling "between" and assigning meaning (a name) to it, so that is how you need to declare it.
