### ISSUE TITLE
As a user, I use the values filter to remove extreme values and would like that to be applied before event detection so that extreme values aren't considered

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#404]
I just performed an event detection evaluation for ABRN1 (same data as always) applying this filter:

```yaml
values:
  minimum: 1.0
  maximum: 10.0
```

The complete declaration is below; supporting data is in the `GitHub_382` `WRES Redmine Large Data Sets` Google Drive folder. That change did not impact the identified events, but did remove pairs from the evaluation. In other words, the `values` filter is applied AFTER event detection.

When I talked about this with James, he said that the main use case for `values` that he foresees is to remove unreasonable numbers (e.g., negative values indicating missing that aren't otherwise recognized as missing) from the time series, so perhaps it should be applied BEFORE event detection.

We can continue the discussion here and, if necessary, implement the change. I'm calling this a feature at this point, not a bug, but am open to negotiations.

Thanks,

Hank 

==========

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: AHPS Streamflow Forecast
  sources:
    - uri: https://WRDS/api/rfc_forecast/v2.0/forecast/streamflow
      interface: wrds ahps
  variable: QR
  type: single valued forecasts

features:
 - {observed: 'ABRN1' , predicted: 'ABRN1' }

time_scale:
  function: mean
  period: 24
  unit: hours

reference_dates:
  minimum: 2000-08-07T23:00:00Z
  maximum: 2015-08-08T23:00:00Z

event_detection: observed

values:
  minimum: 1.0
  maximum: 10.0

metrics:
  - pearson correlation coefficient
  - sample size
  - name: time to peak error
    summary_statistics:
    - median
    - minimum
    - maximum
    - mean

output_formats:
  - csv2
  - png
  - pairs
```

**Comment by james-d-brown** [comment]
Thanks, Hank.

On the whole, I think these filters should not be applied before event detection, but I think there is a reasonable case for the `values` being an exception because the goal of that filter is to completely ignore any unreasonable values from an analysis. More generally, applying filters, such as the `season`, before event detection probably isn't a good idea as it will introduce a discontinuity into the time-series for event detection, whereas applying the filter post-detection seems reasonable (and is the case now).

Regardless, I think the wiki probably needs a section to explain what filters and transformations are applied before event detection, notably `valid_dates`, `time_scale` and, with this ticket, `values`.

**Comment by HankHerr-NOAA** [comment]
Makes sense to me. Thanks,

Hank

**Comment by james-d-brown** [comment]
Doing this one. Two parts: 1) code/test; 2) wiki documentation, as above.

**Comment by james-d-brown** [comment]
Have pushed/merged and updated the wiki:

https://github.com/NOAA-OWP/wres/wiki/Event-detection#what-filters-or-transformations-are-applied-to-the-time-series-data-before-event-detection

This is ready for UAT.

**Comment by HankHerr-NOAA** [comment]
Taking a look at this using a standalone. I'll do a with and without `values` filter to judge the effect.

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Taking longer to test than expected. I'm struggling to find `values` that doesn't cause the evaluation to error out due to no stats computed for any pools.

Hank

**Comment by HankHerr-NOAA** [comment]
So I can't just throw any old `values` filter at an evaluation using event detection and assume it will work. I need to look carefully at the data.

Examining the observations, most of them are in the 100-1000 CFS range, with some into the 1000s or even about 10,000. The evaluation is performed at a 24-hour scale matching the observations, so I don't have to think about rescaling effects (I can't recall if event detection is applied before or after rescaling, but I didn't have to worry about that for this test). I decided to treat values over 10,000 as "extreme" and let `values` be declared to eliminate that extreme:

```yaml
values:
  minimum: 0.0
  maximum: 10000.0
```

Without any `values` filter declared, the evaluation identified 64 events. With `values`, 68 events were identified. More events when eliminating extreme observations above 10,000. I suppose anything is possible when removing particularly high flows from consideration. (NOTE: If I define values to be [1000,10000] I get 77 events. Even more. Hmmm...)

On the other hand, there are 263 pairs for the run without `values` and 227 pairs for the evaluation with `values`. Looking at the pairs for the run without the filter, I do see a quite a few pairs with data above 10,000 CFS. When the `values` filter is applied, I see no pairs with an `observed` or `predicted` above 10,000. That's good.

So I think this is behaving as expected, but admit that its hard for me to do a really close check against the numbers, because I don't know how event detection should be impacted. However, I can say that its very sensitive to the `values`. 

Thanks,

Hank
