### ISSUE TITLE
As a user, I want to be able to specify URL parameters for the feature_service as we are currently allowed to do for data sources

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#410]
This is valid for sources:

```yaml
predicted:                                                            
  label: NWM MR single-valued forecast                                                           
  sources:                                                                               
    uri: https://BLAH/                                  
    interface: nwm medium range deterministic channel rt conus                                    
    parameters:                                                                          
      location_nwm_crosswalk_dataset: '1.2'                                              
  variable: streamflow                                                               
  type: single valued forecasts 
```

The URL parameter, `location_nwm_crosswalk_dataset=1.2`, will be added to the URL when obtaining data.  However, we don't have that capability for the `feature_service`. I would like for this to work:

```yaml
feature_service:
  uri: https://BLAH/api/location/v3.0/metadata
  parameters:
    location_nwm_crosswalk_dataset: '1.2'
```

In the above scenario, I'm expecting the parameters `location_nwm_crosswalk_dataset=1.2` to be appended to the end of the request for features. In WRDS, this option instructs WRDS to obtain the old, 1.2 crosswalk.  

This is a low priority ticket, since it does not come from a user and a work-around exists. Its only really applicable if we want to keep getting the same output from old evaluations that used the feature service to obtain the crosswalk. No user has asked for this. The work-around is defining the crosswalk in the declaration.

See VLab ticket 142704 for the genesis of this requirement. Thanks,

Hank
