### ISSUE TITLE
As a developer, I want a jacoco test coverage report on every build

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#419]
Given a build pipeline
When each build completes with associated junit tests
Then I expect to see a jacoco code coverage report in the `build/reports` directory
So that I can eventually display this information on the github landing page

( Last step isn't necessarily required to complete this ticket, but would be nice. )

**Comment by james-d-brown** [comment]
Was working at some point, still has the jacoco plugin applied in ourt `build.gradle`, but it appears not to generate a report on each build. Step (1): test the `jacocoTestReport` task. Step (2): if it doesn't work, fix it, if it does, configure to run on each build.

https://docs.gradle.org/current/userguide/jacoco_plugin.html

**Comment by james-d-brown** [comment]
Context is that a solutions architect working with the customer was asking about code coverage recently and we couldn't immediately point to this.

**Comment by james-d-brown** [comment]
Second part of this ticket (display on landing page) can be completed in #378.

**Comment by HankHerr-NOAA** [comment]
Found the command, `./gradlew testCodeCoverageReport`, in VLab. It runs. The report is generated under, `build/reports/jacoco/testCodeCoverageReport`. The "Missed Instructions" is reported at "141,133 of 317,367", for a coverage of 55%.  "Missed Branches" is reported at "15,974 of 29,600", for a coverage of 46%.

There is an XML file, `testCodeCoverageReport.xml`, that is generated with the overall results at the very end of the document:

```xml
<report name="wres">
... SNIP ...
<counter type="INSTRUCTION" missed="141113" covered="176254"/>
<counter type="BRANCH" missed="15974" covered="13626"/>
<counter type="LINE" missed="33478" covered="47025"/>
<counter type="COMPLEXITY" missed="17433" covered="12207"/>
<counter type="METHOD" missed="6652" covered="7842"/>
<counter type="CLASS" missed="225" covered="860"/>
</report>
```

Can we get our unit testing workflow to produce the `testCodeCoverageReport` complete with a badge of some kind based on the overall results?

Hank

**Comment by james-d-brown** [comment]
This was originally part of the build pipeline, but it was removed for reasons that I forget. You may want to dig into the history of that to discover why it was removed from the build pipeline.

**Comment by HankHerr-NOAA** [comment]
Found this:

https://github.com/marketplace/actions/jacoco-badge-generator

It refers to a `jacoco.csv`, which will require a change to our `build.gradle` to output. See

https://github.com/marketplace/actions/jacoco-badge-generator#running-jacoco-via-gradle

As for James's comment about the capability being removed at some point and finding the reason...

The VLab ticket where we added the report is 111518. As a byproduct of that ticket, the `testCodeCoverageReport` task was added to our Gradle build and the VLab Jenkins server was updated to run it. 

After reading through a GitHub ticket which pointed me to the `commitChecks.yml`, I confirmed that the `testCodeCoverageReport` is included in our current workflow:

```yml
    # Run and build using gradle
    # Disable aggregateJavaDocs
    - name: Run build
      run: ./gradlew distZip testCodeCoverageReport javadoc
```

That `testCodeCoverageReport` works for me from the command line. Let me take a look at a recent commit check to see if there is any sign that it is being executed.

Hank

**Comment by HankHerr-NOAA** [comment]
Thanks, Evan. I'm currently focusing on what is happening with our current setup. It should be generating a report, but what happens to it?

Looking at

https://github.com/NOAA-OWP/wres/actions/runs/13907576307/job/38914107971

I can see the task being run:

```
2025-03-17T18:54:40.4724536Z [36;1m./gradlew distZip testCodeCoverageReport javadoc[0m
```

But did it really run? Well, when I run `.gradlew testCodeCoverageReport`, I don't see much indication of what happens from the command line. What I really need to do is see if reports are generated. I don't know much about how these workflows operate. Are files generated with a commit check discarded afterwards? Maybe this is where Evan's `jacoco-report` comes in.

Looking,

Hank

**Comment by HankHerr-NOAA** [comment]
So `jacoco-report` will provide a report in a commet of the PR and `jacoco-badge-generator` will generate a badge. My original goal was to get at that badge so that any developer, auditor, whoever, can just visit the landing page and see what kind of coverage we currently have. Maybe we need to do both.

Anyway, I'd still like to see what happens to the `reports` since the `testCodeCoverageReport` is being run,

Hank

**Comment by epag** [comment]
The files are not current being saved. If you want to reference a file (They would still be created) you are going to need to archive them into the run like I am doing for the various build artifacts

**Comment by epag** [comment]
The path that they are in is `wres-*/build/reports/jacoco/testCodeCoverageReport `

**Comment by HankHerr-NOAA** [comment]
That answers that question. Thanks, Evan! The report I actually want is the top-level one, which is just, `build/reports/jacoco/testCodeCoverageReport`. 

I need to step away for a bit, but will take a look at the actions being referenced in the links Evan and I mentioned and see what I can make of it. I was originally planning to tackle this today, but if its a low enough hanging fruit, I might.

Hank

**Comment by epag** [comment]
It should be pretty straight forward.

Just for future knowledge github actions try to be a slim as possible. With that in mind, logs are the only thing you get by default, everything else needs to be explicit.

**Comment by HankHerr-NOAA** [comment]
For future reference, adding this to the `build.gradle` will give us a CSV:

```
testCodeCoverageReport {
    reports {
        csv.required = true
    }
}
```

The CSV:

`build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv`

Hank

**Comment by HankHerr-NOAA** [comment]
If we add this to the `commitChecks.yml` after the test report is generated, I think it will create a badge:

```yaml
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg
```

I'm hoping this creates the folder,

https://github.com/NOAA-OWP/wres/tree/94467c2795c54772e4ea27ed67698de50b949c0f/.github/badges

I would then have to figure out how to refer to badges under that location from the README. First step is to get the CSV to be output. Let me edit the `build.gradle`, test it, and then push/PR/merge. I can then play around with the settings to see if I can get the badge to be published to a location that I can reference in the README.

Hank

**Comment by HankHerr-NOAA** [comment]
Pull request is in: https://github.com/NOAA-OWP/wres/pull/458. The CSV change is pretty benign: it just creates a .csv next to the already generate .xml. That .csv is what the badge generator relies on. Once the checks pass, I'll merge.

In the mean time, I now need to figure out how to edit the workflow (i.e., the mechanics).

Hank

**Comment by HankHerr-NOAA** [comment]
Pull request merged. The build.gradle has been updated.

I'm now going to work in a fork to see if I can get the badge created.

Hank

**Comment by HankHerr-NOAA** [comment]
The badge is placed in a location where it would then need to be committed to the repository. You can see that happening in the example here:

https://github.com/marketplace/actions/jacoco-badge-generator#example-workflow-1-generate-instructions-or-c0-coverage-badge-only

Is it possible to specify a location where it would be recorded as part of the results? Evan mentioned, "you are going to need to archive them into the run like I am doing for the various build artifacts." I noticed that archiving in the workflow. Let me see if I can piggy back off of that.

Hank

**Comment by HankHerr-NOAA** [comment]
Struggling to get the badge into a location where I can actually see it, I video chatted Evan.  He mentioned that just having the coverage reports as a comment would be good. Currently, I have the coverage report being output to the Action results page in my Fork; again, see my screenshot above.

So I looked at `jacoco-report`. It requires a GitHub token in order to run, and I'm leery about putting anyone's token in a workflow just to get a coverage report as a comment in a PR. Evan then pointed me to the default token in a workflow:

```
 github-token: ${{ github.token }}
```

I'll test jacoco-report with that to see if I can make that work,

Hank

**Comment by HankHerr-NOAA** [comment]
When using `github.token`, the issue comment failed to post. The reported error was,

```
Error: HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
```

From a web search, that appears to be because the default `github.token` does not have the needed permissions. I found a couple of websites that recommended add `permissions` to the workflow. I'm testing it now,

Hank

**Comment by HankHerr-NOAA** [comment]
So I am now able to get a comment on the PR reporting the overall project test coverage. It looks like this if there are no failing checks for coverage:

![Image](https://github.com/user-attachments/assets/80133277-331f-4f77-a175-6c1ab1b4756f)

It looks like this if I add options to impose a test on coverage and it fails:

![Image](https://github.com/user-attachments/assets/7d49efe0-09b2-4b69-a2de-8ddef6812f01)

Normally, if code were committed, there would be a separate % reported for the specific change. However, I'm just committing changes to the workflow.  

Overall, here is what I've added to the `commitChecks.yml` workflow in my fork:

```yaml
...
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write
....
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 60
        min-coverage-changed-files: 60
```

Note the `pull-requests` permission setting and the `min-coverage*` settings which are imposing a check for 60% coverage (ours is about 55%). 

Bottom line,

- I can get jacoco-badge-generator to create a report that shows up in the Action.
- I can use jacoco-report to create a report that shows up as a PR comment.
- I cannot get the badge to show up, unless I commit the badge to the repository. This might be possible using a `permissions` change, now that I know such a thing exists. 

Evan commented that the badge may actually not be good to show given its only 55%, but I'm not sure. Anyone what to share their opinion? Do we want the badge in the repo so that I can reference it in the README.md?

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Also, I'm wondering if we really would want the badge to be a file in the repository. In fact, I wonder if that would lead to an infinite loop: a commit/push triggers the workflow that results in the commit/push of the badge which triggers the workflow again.  There is probably a way to avoid that, but I think the better solution is either to find another place where I can create the badge that doesn't require a commit/push or just not worry about the badge at all and relying on the comment and/or Action report. 

Related... Do we prefer the PR comment, the Action report, or both? The PR comment snapshot is shared in my previous comment while the Action report is shared in [this comment](https://github.com/NOAA-OWP/wres/issues/419#issuecomment-2733328498). 

Thoughts?

Hank

**Comment by james-d-brown** [comment]
I don't see how you can impose a minimum coverage of 60% overall when the codebase is currently at 55%. Depends what these settings do w/r to the PR. Changed files, OK.

As an aside, 60-80% is a good target for a large-ish codebase, so 55% is pretty close. Anything above 80% is probably a misspent effort and above 90% is silly.

What is the "badge" in this context, just a little png or something? Isn't it hosted somewhere else?

**Comment by HankHerr-NOAA** [comment]
I was just using 60% to force a failure in order to share the screenshot. I'm not proposing we use it. If we do include checks, then I'm thinking 50% for the code base and something higher (60%? 75%?) for changes.

The badge would be an image (SVG) that shares the percent covered in a form that can be referenced from the README.md, similarly to how the current badge is shared.  I can get the `jacoco-badge-generator` to run in the workflow and see its impact on the Action report (again, see above), but I can't get at the badges it creates, because it wants the badge to be committed to the repo. At least based on the examples. For example,

https://github.com/marketplace/actions/jacoco-badge-generator#example-workflow-1-generate-instructions-or-c0-coverage-badge-only

Thanks,

Hank

**Comment by epag** [comment]
My thoughts as follows:

- I am against having to do a commit every time in order to get a badge to appear on the README unless it is providing a high degree of value (But im hard pressed to think of any badge that would meet my standards)
- I am not against having a badge on the front page, just don't think it brings enough value to warrant a large time investment 
- I see no reason why we shouldn't have the commit message and also the action summary for the coverage report

**Comment by HankHerr-NOAA** [comment]
Taking a brief look at other ways to get at the badge...

I have confirmed that I can upload the badges to an artifact associated with the action. It goes into a zip file and I doubt the README can reference it, but I guess its something. And it does confirm that the badge images are created, which is nice.

Including both is easy enough, so I'll do that. I'll look into the badge a big longer, but am splitting my attention between this an WRES GUI discussion action items. 

Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
I'm bailing on the idea of a badge. Unless we use the repository as a middle man, meaning one commit/push per badge update, or dump the badge to an S3 bucket somewhere, I don't see a good way to get the badge to display with the README.md. And, without that, I see no reason to generate the badge at all.  

Just so I have the workflow YAML somewhere to reference later if desired, this will create the badges and create a `jacoco_badge.zip` artifact to store the one badge next to the other build artifacts from `commitChecks.yml` (that artifact can easily be updated to store both badges by adding both files to `path`):

```yaml
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv
        badges-directory: build
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg

    # Archive the artifacts created from this build
    - name: Archive jacoco badge
      uses: actions/upload-artifact@v4
      with:
        name: jacoco_badge
        path: build/jacoco.svg
```

I'm now going to finalize the change I plan to make to the workflow in my fork. Once I convince myself its ready, I'll add it to the main code base via the standard pull request. 

Hank

**Comment by HankHerr-NOAA** [comment]
The changes to make to the workflow are shown below; the existing "Run build" action is included in order to provide context for where the change will be made (immediate after). Also included is the `pull-requests: write` addition where the `permissions` are set. 

The latest version of `jacoco-report` is 1.7.1 and its hardcoded below. The version for `jacoco-badge-generator` is the latest available in version 2 (appears to be 2.11.0 currently). **If there is a better approach to handling the versions in the workflow, please let me know.**

For `jacoco-report`, I have it reporting a problem to the PR if the overall coverage is under 50% (which would take quite a lot to trigger given current coverage is 55%) or if the new-code coverage is under 60%. A merge of the PR is not rejected when this happens, to the best of my knowledge. Rather, it just flags it as an issue in a comment. Its up to us to decide if to go through with the PR merge. **If anyone recommends different settings, please let me know.**

**If anyone has any recommended changes to any of this, please let me know.** I'd like to push/merge these changes to the wres repo before the end of the day if possible. 

Last note: Evan mentioned to me directly the idea of performing a coverage check based on change in current coverage before and after. If it reduces by more than X%, then flag that as a problem. I'm not going to tackle that now. However, I can create a future ticket for it if anyone wants me to.

Thanks,

Hank

==========

```yaml
...

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

...

    # Run and build using gradle
    # Disable aggregateJavaDocs
    - name: Run build
      run: |
        ./gradlew build
        ./gradlew distZip testCodeCoverageReport javadoc

    # Add a Jacoco report to the action output using badging tool.
    # The badges can be added readily; see a comment in #419. 
    # However, we have no way to view them in the README.md.
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv

    # Add coverage report to the pull request as comment.
    # Basic coverage checks are implemented.
    - name: Add coverage to PR as comment
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 60
```

**Comment by HankHerr-NOAA** [comment]
I noticed that everywhere else in the workflow, we restrict ourselves only to the major version number, so I'm currently testing this change in my fork:

```yaml
      uses: madrapps/jacoco-report@v1
```

If it still works, I'll update the YAML snippet I shared in my previous comment to use "v1". I'll then make the changes in the wres repo and then push and submit a PR.

Hank

**Comment by HankHerr-NOAA** [comment]
Nope, that didn't work. It doesn't appear to grab the correct version, because what it used reported this error:

`Unexpected input(s) 'paths', valid inputs are ['path', 'token', 'min-coverage-overall', 'min-coverage-changed-files']`

That's a very restrictive list of inputs, and note that `paths` was shortened to `path`. That seems like a breaking change. Anyway, I'll stick with the fully qualified "1.7.1" since it works.

I'm going to make the change now,

Hank

**Comment by HankHerr-NOAA** [comment]
The pull request is in and checks are running now:

https://github.com/NOAA-OWP/wres/pull/459

I've marked that PR as fixing this ticket, hopefully forcing this ticket closed if it goes through. I don't plan to do any more for this ticket, but, again, if we want to implement logic to look at change in coverage instead of comparing against fixed values for overall and new, please let me know and I'll create a ticket.

Waiting for the PR to complete it checks,

Hank

**Comment by HankHerr-NOAA** [comment]
The PR checks failed because of issues with the "Compile external-service-tests" which I didn't intentionally change. 

Let me see if I have a stray character or something that could cause the issue,

Hank

**Comment by HankHerr-NOAA** [comment]
First, I do notice this for the `jacoco-report` job, which does  not explain the external service tests error:

```
Run madrapps/jacoco-report@v1.7.1
Event is push
base sha: 0000000000000000000000000000000000000000
head sha: e5de48cdf5dfae410ef05be973226f685b72700c
Error: HttpError: Not Found - https://docs.github.com/rest/commits/commits#compare-two-commits
```

The base sha is bad. I'm not sure where the base sha comes from. 

Looking at the rest of the workflow, here is what I now have:

```yaml
    # Run and build using gradle
    # Disable aggregateJavaDocs
    - name: Run build
      run: |
        ./gradlew build
        ./gradlew distZip testCodeCoverageReport javadoc

    # Add a Jacoco report to the action output using badging tool.
    # The badges can be added readily; see a comment in #419. 
    # However, we have no way to view them in the README.md.
    - name: Generate Jacoco coverage report in Action
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv

    # Add coverage report to the pull request as comment.
    # Basic coverage checks are implemented.
    - name: Add Jacoco coverage report in PR comment
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 60

    # Confirm the test code inside wres-external-services-tests zip compiles
    - name: Compile external-services-tests
      run: |
        cd wres-external-services-tests
        ../gradlew installDist
        cd build/install/wres-external-services-tests
        ./gradlew testClasses
```

Here is what was there before (and is in master now since my PR was rejected):

```yaml
    # Run and build using gradle
    # Disable aggregateJavaDocs
    - name: Run build
      run: |
        ./gradlew build
        ./gradlew distZip testCodeCoverageReport javadoc

    # Confirm the test code inside wres-external-services-tests zip compiles
    - name: Compile external-services-tests
      run: |
        cd wres-external-services-tests
        ../gradlew installDist
        cd build/install/wres-external-services-tests
        ./gradlew testClasses
```

Anyone see a problem with this? I don't.

Hank

**Comment by HankHerr-NOAA** [comment]
Ignore my worry about the `base sha` being all 0s; that corresponds to the commit. The actually pull request gave me a reasonable SHA. I'm guessing that means, when `commitChecks.py` runs for a commit, we can expect that may or will fail because there is no base sha. However, for pull requests, the base sha exists, so it succeeds. 

Does that makes sense? I'm asking, because I'm not really sure why the base sha would not exist for a commit. 

Is there anything we should do about this? Can I restrict the report to only be for a pull request and not a commit?

Back to the problem at hand: I can't build external tests.

Hank

**Comment by HankHerr-NOAA** [comment]
Well, I was able to reproduce the problem locally; pulling the pertinent commands from my history:

 1104  18 Mar 2025 19:50:47 cd wres-external-services-tests/
 1106  18 Mar 2025 19:51:03 ../gradlew installDist
 1118  18 Mar 2025 19:54:42         cd build/install/wres-external-services-tests
 1119  18 Mar 2025 19:54:44         ./gradlew testClasses

That mirrors what is done in the workflow. The last command above fails complaining about not being able to find things in `wres.http`. For example:

```
... error: cannot find symbol                                                                                                                                                           
    private static final WebClient WEB_CLIENT = new WebClient( WebClientUtils.defaultTimeoutHttpClient() );                                                        
                         ^                                                                                                                                         
  symbol:   class WebClient                                           
  location: class NwisTest                                                                                                                        
```

I note that this is run immediately after the Gradle build, so let me back it up a bit and run that first.

Hank

**Comment by HankHerr-NOAA** [comment]
So that makes the difference. I need to run it very specifically in this order:

```
./gradlew distZip testCodeCoverageReport javadoc
cd wres-external-services-tests/
../gradlew installDist
cd build/install/wres-external-services-tests
./gradlew testClasses
```

I admit to not testing the changes in the context of the full workflow: I believe I only needed the build, so I commented out everything from the external service tests on.  Apparently, by inserting the jacoco stuff in between the build and external services tests, I broke the external services tests check, though I have no idea why.

I guess I need to return to the fork and figure this out.

Hank

**Comment by HankHerr-NOAA** [comment]
If I can reproduce the error in the fork, I'm going to move the jacoco stuff to after the external services test check, and modify the report location to be able to find the report using an absolute path. I think this should work based on something I tested before:

```
${{ github.workspace }}/**/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
```

Hank

**Comment by HankHerr-NOAA** [comment]
So it seems as though there is a limited memory what a build creates in the workflow, because the first Jacoco report fails to find the coverage report if I move it to after the external service test.  However, the external services test succeeds. 

I'll have to look more into this tomorrow. What I'll try:

1. Am I specifying the correct report location when I use the `${{ github.workspace }}/**/build/reports/...` path?
2. Is there a flag to get the build results to live longer? If that's even the cause.
3. How fast will it run if I create a separate workflow for the coverage reports? Is it quick enough to add it to the requirements of a PR?

More tomorrow,

Hank

**Comment by epag** [comment]
I sent this in a DM, but summarizing here:

- First, its isn't the external services tests themselves that are failing, it is failing to compile the code itself `Compile external-services-tests`. I'm not sure why this would be the case, but see my next point for why I think it doesn't really matter. 
- I strongly advise against putting the test coverage check under the build step all-together, that is now how these checks are structured. We build the code, store the various artifacts we will need later jobs and then those jobs will download what they need from the build. This way multiple workflows can be executed asynchronously 
![Image](https://github.com/user-attachments/assets/2f280709-ad3f-4205-82b6-2abd8ce02445)

So I would recommend adding whatever testCodeCoverage reports that you need into the artifact section of the build pipeline and then create a new job, like systests, that relies on build. That way the work can be done more async and a failing testcodecoverage step does not prevent systests from being run on a commit.

![Image](https://github.com/user-attachments/assets/5c40debf-efd4-487e-86d0-92aae7f44d0b)

**Comment by epag** [comment]
We could honestly even break up systests to its component parts and increase performance by like a minute now that I am thinking about it

**Comment by HankHerr-NOAA** [comment]
I got the code coverage reports to work using the YML I shared below, which establishes the `codeCoverageReport` job independently of `Build` and `systests`. I had to add the CSV and XML code coverage report files to the build artifacts (see below) to make it work.  I need to clean up the changes just a bit, test it again in my fork, and, if it all works out, I'll update the wres repo workflow with these changes in an hour or so. 

Thanks,

Hank

==========

```yaml
    # Archive the artifacts created from this build
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          checksum.txt
          build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv
          build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          build/distributions/wres-*.zip
          wres-*/build/distributions/wres-*-*.zip
          systests/build/distributions/systests-*.zip
          scripts/build/distributions/wres-admin-scripts-*.zip

  # ========================================================
  # Generate the code coverage reports. 
  # ========================================================
  codeCoverageReport:
    needs: Build
    runs-on: ubuntu-latest
    
    # pull-requests write permission needed for Jacoco report in PR comment.
    permissions:
      contents: read
      pull-requests: write  

    steps:

    # Download artifacts from previous step
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ github.token }}

    # Add a Jacoco report to the action output using badging tool.
    # The badges can be added readily; see a comment in #419.
    # However, we have no way to view them in the README.md.
    - name: Generate Jacoco coverage report in Action
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build-artifacts/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.csv

    # Add coverage report to the pull request as comment.
    # Basic coverage checks are implemented.
    - name: Add Jacoco coverage report in PR comment
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: build-artifacts/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 60
```
