### ISSUE TITLE
As a user, I to make corrections to the code and/or wiki to better reflect reality when employing combination, operation, and aggregation

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#423]
The full test declaration is below; it was picked at random and then I started toying with different `combination` options. 

Specifically, `aggregation` "none" is not deserialized successfully even though the schema indicates its valid. For example, 

```yaml
    combination: 
#      operation: intersection
      aggregation: none
```

yields this exception:

> Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type wres.config.yaml.components.TimeWindowAggregation from String "none": not one of the values accepted for Enum class: [maximum, average, minimum]

Also, when `aggregation` is valid, the validation error implies that a default `operation` of `union` is selected:

```yaml
    combination:
#      operation: intersection
      aggregation: maximum
```

yields this validation error (and only this error):

> Event detection was declared with an 'operation' of 'union' and an aggregation method of 'maximum', which is not valid. Please remove the 'aggregation' method, declare an 'aggregation' method of 'none' or change the 'operation' to 'intersection'. An explicit 'aggregation' method is only valid when the 'operation' is 'intersection'.

That message appears to indicate that a default of "union" for operation is assumed. I don't think that's true based on the wiki, and based on validation errors for the declaration in [this comment](https://github.com/NOAA-OWP/wres/issues/382#issuecomment-2665964647).

I think this ticket can be resolved when:

1. "none" is properly parsed for the `aggregation`.
2. If `operation` is not included, a validation error message tells me it needs to be included **in all cases**, matching the wiki.  This is not currently true if I specify `aggregation: maximum` as described above. 

Thanks,

Hank

==========

```yaml
label: Testing Event Based
observed:
  label: OBS Streamflow
  sources: /home/ISED/wres/wresTestData/issue92087/inputs/ABRN1_QME.xml
  variable: QME
  feature_authority: nws lid
  type: observations
  time_scale:
    function: mean
    period: 24
    unit: hours

predicted:
  label: "19161749 RetroSim CSVs"
  sources:
  - /home/ISED/wres/nwm_3_0_retro_simulations/wfo/OAX/19161749_nwm_3_0_retro_wres.csv.gz
  variable: streamflow
  feature_authority: nwm feature id
  type: simulations

features:
  - {observed: ABRN1, predicted: '19161749'}

time_scale:
  function: mean
  period: 24
  unit: hours

#reference_dates:
#  minimum: 2000-08-07T23:00:00Z
#  maximum: 2015-08-08T23:00:00Z

#event_detection: observed
event_detection:
  dataset:
    - observed
    - predicted
  parameters:
    window_size: 4800
    start_radius: 0
    half_life: 480
    minimum_event_duration: 0
    duration_unit: hours
    combination:
      operation: union
      aggregation: 'none'

metrics:
  - time to peak error
  - sample size
  - pearson correlation coefficient

output_formats:
  - csv2
  - png
```
