### ISSUE TITLE
As a user, I want to correlate thresholds with features when the thresholds use a different feature authority than any evaluated dataset

### ISSUE THREAD

**Issue by james-d-brown** [NOAA-OWP/wres#427]
Given an evaluation that uses external thresholds, such as the water resources data service thresholds service
When the thresholds use a feature authority that differs from the feature authority of any evaluated dataset
Then the evaluation should "just work", providing a `feature_service` has been declared and it allows for feature correlation

**Comment by james-d-brown** [comment]
For example, an evaluation of NWM data (NWM feature authority) against USGS data (USGS feature authority) using NWS thresholds (NWS feature authority, not part of any evaluation dataset).

Currently, declaration like this is required:

```
threshold_sources:
- uri: https://nwcal-wrds.nwc.nws.noaa.gov/api/location/v3.0/nws_threshold
  operator: greater
  apply_to: observed
  type: value
  parameter: flow
  provider: NWS-NRLDB
  rating_provider: NRLDB
  feature_name_from: predicted
```

It would be preferred that `feature_name_from` can be omitted in the presence of a `feature_service` that allows for an indirect correlation to be established between one or all of the evaluation datasets and the feature authority of the threshold source (again, the `feature_service` being required in this case). There are still situations where the `feature_name_from` may be preferred or required, but it would be nice if the wres could do the correlations when the feature authority of the thresholds differs from that of any dataset.
