### ISSUE TITLE
As a user, I want an evaluation to succeed if the data found is for a variable alias, but not for the variable name, itself

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#43]
See WRES User Support ticket #132594.  The request is, if data is only found for one of the `variable` `aliases`, but not for the `variable` `name`, then the evaluation should not complain about not finding the named variable.  In other words, aliases are treated equally with the named variable when checking to see if matching data is found.

Note that an example of the exception that occurs when the named variable is not found in the data is the following:

    Caused by: wres.config.yaml.DeclarationException: The declared variable names are inconsistent with the ingested data sources in one or more contexts: 
    - The declared 'name' of the 'variable' for the 'predicted' dataset was 'HG', but this could not be found among the variable names of the ingested data sources, which were: [HP].

In this case, HP is one of the aliases, but the named variable HG is not found, so the WRES throws the exception, above. The change would be for WRES to search through the aliases, as well, and only throw the exception if neither the named variable or one of the aliases is found.

Thanks,

Hank

**Comment by james-d-brown** [comment]
Looking at this.

As an aside, I don't think we should reference hidden user support tickets here. When we need to create a dev ticket to resolve a vlab user support ticket, we should reproduce everything here that is necessary so that the github ticket is completely self-contained.

Would be good to have the dataset to reproduce the exact issue here, even though it can be reproduced approximately (same issue, different data/declaration) without much effort.

**Comment by HankHerr-NOAA** [comment]
Declaration is below, NWC URLs omitted,

Hank

=====================================

```yml
label: USGS Stages against OHRFC Forecast Stages
observed:
  label: USGS NWIS Stage Observations
  sources:
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
    interface: usgs nwis
  variable: "00065"
  type: observations
predicted:
  label: WRDS AHPS API Stage Forecasts
  sources:
    uri: https://[WRDS]/api/rfc_forecast/v2.0/forecast/stage
    interface: wrds ahps
  variable:
    name: HG
    aliases: [HP, HT]
    label: stage
  type: single valued forecasts
features:
  - {predicted: GYLP1}
feature_service:
  uri: https://[WRDS]/api/location/v3.0/metadata
unit: FT
reference_dates:
  minimum: 2024-07-03T00:00:00Z
  maximum: 2024-07-17T00:00:00Z
valid_dates:
  minimum: 2024-07-03T00:00:00Z
  maximum: 2024-07-17T00:00:00Z
lead_times:
  minimum: 0
  maximum: 120
  unit: hours
metrics:
  -  bias fraction
duration_format: days
output_formats:
  - csv2
  - pairs
  - png
```
