### ISSUE TITLE
As a user, I would like a more efficient approach to declaring daily time pools for 30-, 60-, and 90-day evaluation than one custom declaration per pool

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#435]
For the routine evaluations we are investigating, we need 30-, 60-, and 90-day time pools, with daily lead time pools out to 10 days for each one.  Since we are mixing reference date periods, I need to declare these as custom time pools. However, currently each custom time pool needs to map to exactly one pool; `lead_time_pools` is not allowed to created regularly spaced lead time pools for each. Hence, I need 30 (3 evaluation periods x 10 lead time pools each) custom time pools.

This ticket can be resolved when we have a more efficient approach to declaring such pools, either using a top level `lead_time_pools` with each `time_pools` entry, allowing for `lead_time_pools` declared in each `time_pools` entry, or another approach identified by the developer. Thanks,

Hank

**Comment by james-d-brown** [comment]
Or, since the goal is more than one regular sequence, expanding the regular sequences from 1 to N. For example:

```
lead_times:
  minimum: 1
  maximum: 90
  unit: days
lead_time_pools:
  period: 1
  unit: day
reference_dates:
  minimum: 2551-03-17T00:00:00Z
  maximum: 2551-03-20T00:00:00Z
reference_date_pools:
  - period: 30
    unit: days
  - period: 60
    unit: days
  - period: 90
    unit: days
```

**Comment by HankHerr-NOAA** [comment]
Yep, that would satisfy the requirement,

Hank

**Comment by james-d-brown** [comment]
Looking at this, since it's related to a user support ticket and shouldn't be too hard.

**Comment by james-d-brown** [comment]
This will require some additions to the user support wiki too.

**Comment by james-d-brown** [comment]
UAT bucket, but there is also a documentation task for this one.

**Comment by HankHerr-NOAA** [comment]
James:

Have you added any documentation for `reference_date_pools`, yet? Or would you prefer I do that?

Hank

**Comment by HankHerr-NOAA** [comment]
Yes, you did. I found here:

https://github.com/NOAA-OWP/wres/wiki/Declaration-Language#91-how-do-i-declare-a-regular-sequence-of-temporal-pools

Hank

**Comment by HankHerr-NOAA** [comment]
Oh, got it. Saw the one pool and thought, yeah, that's done. My mistake.

Hank

**Comment by HankHerr-NOAA** [comment]
I want to  clarify what this would mean, where I'm leaving the bounds on `reference_dates` unspecified, but spanning 90 days:

```yaml
reference_dates:
  minimum: [~90 days ago]
  maximum: [now]
reference_date_pools:
  - period: 30
    unit: days
  - period: 60
    unit: days
  - period: 90
    unit: days
```

I think this means I'll get `reference_date_pools` of (0, 90) days, (0, 60) days, and (0, 30), (30, 60), (60, 90). Is that correct?

If so, that isn't quite what is needed for the NWM MRF evaluation that lead to this enhancement request, but might be something that the user can live with to avoid having to declare all of the pools explicitly.

Thanks,

Hank

**Comment by james-d-brown** [comment]
> I want to clarify what this would mean, where I'm leaving the bounds on `reference_dates` unspecified, but spanning 90 days:
> 
> reference_dates:
>   minimum: [~90 days ago]
>   maximum: [now]
> reference_date_pools:
>   - period: 30
>     unit: days
>   - period: 60
>     unit: days
>   - period: 90
>     unit: days
> I think this means I'll get `reference_date_pools` of (0, 90) days, (0, 60) days, and (0, 30), (30, 60), (60, 90). Is that correct?
> 
> If so, that isn't quite what is needed for the NWM MRF evaluation that lead to this enhancement request, but might be something that the user can live with to avoid having to declare all of the pools explicitly.
> 
> Thanks,
> 
> Hank

What is `0` in this context? Using your notation, you will get pools (~90 days ago,now], (~90 days ago,~30 days ago], (~90 days ago,~60 days ago], (~60 days ago,~30 days ago], (~30 days ago,now].

But I think I see what you mean. For this application, you want to count backwards from the maximum rather than forwards from the minimum, right? I think this is still the way to declare it, but it would need an additional toggle or rubric. For example, we could allow a `date_pools_backwards: true` to count backwards from the `maximum`, rather than forwards from the `minimum`.

**Comment by HankHerr-NOAA** [comment]
Right. I forgot to treat the counts as negative ("days ago"). 

My biggest concern, for our specific evaluation, was actually pertaining to the 3 x 30-day windows instead of just one.

But, now that you've pointed it out, yes, the negative nature of the counting is a bit hard to wrap my head around. I think you are correct that I was viewing "now" as 0 and then just started writing down what the pools would look like from that base time of "now" looking backwards. That came to me naturally.

If we stick with what comes naturally, then, yeah, we should probably allow for that. Another ticket, right? I don't think it has to hold up 6.30. I just need to make sure I fully understand what I'm declaring before I UAT this ticket.

Hank

**Comment by james-d-brown** [comment]
Yes, another ticket. We could also delay advertising the feature and docs until that is done - probably makes sense vs. announcing and then incrementing in successive releases. In that ticket, we should also double-check that it does the needful for this NWM user story.

**Comment by HankHerr-NOAA** [comment]
Okay. I'll create that ticket tomorrow and remove the announcement from the News item.

Hank

**Comment by HankHerr-NOAA** [comment]
I created #451 for the new looking-backwards feature. 

I'm going to take a look at the ISED evaluations to find one that will work quickly and allow me to test the current capability.

Hank

**Comment by HankHerr-NOAA** [comment]
The complete declaration I'm using is below, with WRDS URL omitted. I posted that as job 2403165486801292984. There were 50 pools identified. Given 5 reference date pools and 10 lead time pools, that's expected. Examining the pools, I see the following 5 distinct reference date pools:

- Earliest reference time: 2024-12-04T00:00:00Z, Latest reference time: 2025-01-03T00:00:00Z
- Earliest reference time: 2024-12-04T00:00:00Z, Latest reference time: 2025-02-02T00:00:00Z
- Earliest reference time: 2024-12-04T00:00:00Z, Latest reference time: 2025-02-02T00:00:00Z
- Earliest reference time: 2024-12-04T00:00:00Z, Latest reference time: 2025-02-02T00:00:00Z
- Earliest reference time: 2024-12-04T00:00:00Z, Latest reference time: 2025-02-02T00:00:00Z

Those appear correct.  The output appears reasonable given that WRES really doesn't know how to display it:

![Image](https://github.com/user-attachments/assets/247786f0-ee42-46b6-8bc5-90f6e6482c2f)

Passes UAT.

BUT... We are not announcing this capability with 6.30. As discussed above, we'll announce it when we have the looking-backwards ability, which is a bit more intuitive, I think. That is #451.  

Let me see if we have a 6.31 milestone. If not, I'll create it and assign this ticket to it leaving it in UAT. For that UAT, see the declaration below and the expected image above.

Hank

==========

```yaml
label: ISED Routine NWM MRF Single Valued For marfc
observed:
  label: USGS NWIS Streamflow Observations
  sources:
  - interface: usgs nwis
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
  variable:
    name: '00060'
predicted:
  label: WRDS NWM MRF Single Valued Streamflow Forecasts
  sources:
  - interface: wrds nwm
    uri: https://WRDS/api/nwm3.0/v3.0/ops/medium_range/
  variable:
    name: streamflow
  feature_authority: nwm feature id
  type: single valued forecasts
unit: ft3/s

# Features
features:
- observed: '01631000'
  predicted: '5907079'

# Time scale
time_scale:
  period: 24
  unit: hours
  function: maximum

# Computations
metrics:
- name: bias fraction
- name: sample size
sampling_uncertainty:
  sample_size: 1000
  quantiles:
  - 0.025
  - 0.975

#Outputs
output_formats:
- format: csv2
- format: png

# Timing and time pools.
reference_dates:
  minimum: '2024-12-04T00:00:00Z'
  maximum: '2025-03-04T00:00:00Z'
valid_dates:
  minimum: '2024-12-04T00:00:00Z'
  maximum: '2025-03-04T00:00:00Z'

lead_times:
  minimum: 0
  maximum: 10
  unit: days
lead_time_pools:
  period: 1
  unit: days
reference_date_pools:
- period: 30
  unit: days
- period: 60
  unit: days
- period: 90
  unit: days
```

**Comment by HankHerr-NOAA** [comment]
I'm tested this in RHEL 7 with job id 6050007069319070152.  The identified pools:

2024-12-04T00:00:00Z,2025-02-02T00:00:00Z
2024-12-04T00:00:00Z,2025-03-04T00:00:00Z
2025-01-03T00:00:00Z,2025-02-02T00:00:00Z
2025-02-02T00:00:00Z,2025-03-04T00:00:00Z

The last pool, Dec 4 - Jan 3, is missing because its older than 90-days. Sigh.  Otherwise, the output appears "reasonable". 

Anyway, the declaration works, but, for final UAT tomorrow using RHEL 8, I need to remember to adjust the dates to be more recent. Thanks,

Hank

**Comment by HankHerr-NOAA** [comment]
Posted job 4101481678864066849 to staging (via proxy, so RHEL 8). Will report back,

Hank

**Comment by HankHerr-NOAA** [comment]
Per the deployment ticket in VLab, I only tested this capability using `reference_date_pools`, not `lead_time_pools` or `valid_date_pools`. I'll let James make the final call, but I think this might need additional UAT for those two types of temporal pools. If so, I'll work on that first thing tomorrow morning. It shouldn't take too much time unless something goes wrong.

Hank

**Comment by HankHerr-NOAA** [comment]
I'll run a couple of quick evaluations testing `lead_time_pools` and `valid_date_pools`. Shouldn't take too long. I just need to do some admin work and eat breakfast first.

Hank

**Comment by HankHerr-NOAA** [comment]
I took an HEFS evaluation and used these `lead_time_pools`:

```yaml
lead_time_pools:
- period: 24
  unit: hours
- period: 7
  unit: days
cross_pair: exact
lead_times:
  minimum: 18
  maximum: 720
  unit: hours
```

I saw the pools I expected including both daily and weekly; a snippet:

> The time windows are: [ TimeWindowOuter[earliestReferenceTime=-1000000000-01-01T00:00:00Z,latestReferenceTime=+1000000000-12-31T23:59:59.999999999Z,earliestValidTime=-1000000000-01-01T00:00:00Z,latestValidTime=+1000000000-12-31T23:59:59.999999999Z,earliestLeadDuration=PT18H,latestLeadDuration=PT42H], TimeWindowOuter[earliestReferenceTime=-1000000000-01-01T00:00:00Z,latestReferenceTime=+1000000000-12-31T23:59:59.999999999Z,earliestValidTime=-1000000000-01-01T00:00:00Z,latestValidTime=+1000000000-12-31T23:59:59.999999999Z,earliestLeadDuration=PT18H,latestLeadDuration=PT186H], ...

I then posted a WRES RFC forecast evaluation with these `valid_date_pools`:

```yaml
valid_dates:
  minimum: '2025-04-01T00:00:00Z'
  maximum: '2025-04-11T04:58:20Z'
valid_date_pools:
- period: 10
  unit: days
- period: 5
  unit: days
```

Again, I saw the expected pools; a snippet:

>  ... TimeWindowOuter[earliestReferenceTime=2025-04-01T00:00:00Z,latestReferenceTime=2025-04-11T04:58:20Z,earliestValidTime=2025-04-01T00:00:00Z,latestValidTime=2025-04-06T00:00:00Z,earliestLeadDuration=PT114H,latestLeadDuration=PT120H], TimeWindowOuter[earliestReferenceTime=2025-04-01T00:00:00Z,latestReferenceTime=2025-04-11T04:58:20Z,earliestValidTime=2025-04-01T00:00:00Z,latestValidTime=2025-04-11T00:00:00Z,earliestLeadDuration=PT0S,latestLeadDuration=PT6H], ...

The output images for both were as expected, with the `valid_date_pools` looking like a spaghetti plot and the HEFS `lead_time_pools` change actually appearing "normal" in a plot of bias fraction:

![Image](https://github.com/user-attachments/assets/220043d9-223e-4320-9513-cd2845bbadbf)

Note the first "186" in the legend refers to the end lead time of the one week lead duration pool while the latter one is the end duration of a one day pool.

Bottom line, this still passes UAT and I'm leaving the ticket marked closed,

Hank
