### ISSUE TITLE
Ability to specify season that crosses a calendar year?

### ISSUE THREAD

**Issue by t3dixon** [NOAA-OWP/wres#441]
Hi there,

Is it possibly to specify a season that crosses a calendar year? For example, Nov-Apr (i.e., wet season in the West).

It seems that WRES runs when I specify a season in the manner, but the months of Jan - Apr are excluded.

Thank you!
-Taylor

**Comment by james-d-brown** [comment]
Hi Taylor,

Nice to hear from you!

Yes, this should work (i.e., wrapping over the year end):

```
season:
  minimum_day: 1
  minimum_month: 11
  maximum_day: 30
  maximum_month: 4
```

Just to double-check, though, I created this toy example:

A time-series in wres csv format:

```
value_date,variable_name,location,measurement_unit,value
1985-01-01T00:00:00Z,QINE,DRRC2,CFS,1
1985-02-01T00:00:00Z,QINE,DRRC2,CFS,2
1985-03-01T00:00:00Z,QINE,DRRC2,CFS,3
1985-04-01T00:00:00Z,QINE,DRRC2,CFS,4
1985-05-01T00:00:00Z,QINE,DRRC2,CFS,5
1985-06-01T00:00:00Z,QINE,DRRC2,CFS,6
1985-07-01T00:00:00Z,QINE,DRRC2,CFS,7
1985-08-01T00:00:00Z,QINE,DRRC2,CFS,8
1985-09-01T00:00:00Z,QINE,DRRC2,CFS,9
1985-10-01T00:00:00Z,QINE,DRRC2,CFS,10
1985-11-01T00:00:00Z,QINE,DRRC2,CFS,11
1985-12-01T00:00:00Z,QINE,DRRC2,CFS,12
```

A declaration that uses this time-series on both sides of the evaluation and writes pairs only:

```
observed: GitHub/441/data/series.csv
predicted: GitHub/441/data/series.csv
season:
  minimum_day: 1
  minimum_month: 11
  maximum_day: 30
  maximum_month: 4
output_formats:
  - pairs
```

Produces these pairs:

FEATURE NAME | FEATURE GROUP NAME | VARIABLE NAME | EARLIEST ISSUE TIME | LATEST ISSUE TIME | EARLIEST VALID TIME | LATEST VALID TIME | EARLIEST LEAD TIME | LATEST LEAD TIME | REFERENCE TIME | VALID TIME | LEAD DURATION | OBSERVED IN CFS | PREDICTED IN CFS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S| | 1985-01-01T00:00:00Z | PT0S | 1 | 1
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S | | 1985-02-01T00:00:00Z | PT0S | 2 | 2
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S | | 1985-03-01T00:00:00Z | PT0S | 3 | 3
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S | | 1985-04-01T00:00:00Z | PT0S | 4 | 4
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S | | 1985-11-01T00:00:00Z | PT0S | 11 | 11
DRRC2 | DRRC2-DRRC2 | QINE | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | -1000000000-01-01T00:00:00Z | +1000000000-12-31T23:59:59.999999999Z | PT-2562047788015215H-30M-8S | PT2562047788015215H30M7.999999999S | | 1985-12-01T00:00:00Z | PT0S | 12 | 12

I think that's what you'd expect, right?

However, if you want to post an example where that isn't the case, I'd be happy to take a look through it...

Cheers,

James

**Comment by t3dixon** [comment]
Hi James!

Thanks for your quick reply! Yeah, your `pairs.csv` output looks good. Interestingly, though, mine only includes data for the months of Nov and Dec:

[pairs.csv](https://github.com/user-attachments/files/19079458/pairs.csv)

I've pasted by config file below. Am I missing something? If needed, I can perhaps email you the actual data I'm testing this with.

Thanks again!

```
observed:
  sources: /input/HOPC1/HOPC1.QME_clip.csv
  variable: QME
  type: observations
  time_zone_offset: '-0600'
  time_scale:
    function: mean
    period: 24
    unit: hours
predicted:
  sources: /input/HOPC1/HOPC1_30day.HEFS.tgz
  variable: QINE
  type: ensemble forecasts
features:
  - {observed: HOPC1, predicted: HOPC1}
unit: CFS
time_scale:
  function: mean
  period: 24
  unit: hours
duration_format: days
lead_times:
  minimum: 0
  maximum: 360
  unit: hours
lead_time_pools:
  period: 24
  frequency: 24
  unit: hours
season:
  minimum_day: 1
  minimum_month: 11
  maximum_day: 30
  maximum_month: 4
#cross_pair: fuzzy  
#pair_frequency:
#  period: 24
#  unit: hours
probability_thresholds:
  values: [0.5,0.8,0.9,0.95]
  operator: greater equal
minimum_sample_size: 1
metrics:
  - sample size
decimal_format: '#0.00000'
output_formats:
  - csv2
  - pairs
  - png
  - csv
```
