### ISSUE TITLE
As a user, I would like to be able to declare reference date pools looking backwards from the maximum reference date

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#451]
Thinking about this from the point of view of running evaluations relative to "now" looking 30-, 60-, and 90-days back, I would like to be able to declare `reference_date_pools` looking backwards from "now" instead of forwards. See #435. 

Currently, if I declare,

```yaml
reference_date_pools:
  - period: 30
    unit: days
  - period: 60
    unit: days
  - period: 90
    unit: days
```

this will result in 30-, 60-, and 90-day pools looking forward from the `reference_dates` `minimum`.  What I would like is to be able to create pools looking backwards from the 'maximum', instead. James mentioned in #435 

> For example, we could allow a date_pools_backwards: true or reverse_pool_sequences: true to count backwards from the maximum, rather than forwards from the minimum.

Thanks,

Hank

**Comment by james-d-brown** [comment]
Makes sense to do this one first for 6.31.

**Comment by james-d-brown** [comment]
I am leaning towards making this a per-sequence setting, rather than a setting across all sequences, partly because it is more flexible and partly because it avoids another high-level declaration option and keeps the setting in context.

In other words, rather than this:

```
reference_date_pools:
  period: 30
  unit: days
reverse_pools: true
```

This:

```
reference_date_pools:
  period: 30
  unit: days
  reverse: true
```

This would provide fine-grained control on individual sequences, like this:

```
reference_date_pools:
  - period: 30
    unit: days
  - period: 60
    unit: days
    reverse: true
  - period: 90
    unit: days
```

Or this:

```
reference_date_pools:
  period: 30
  unit: days
  reverse: true
valid_date_pools:
  period: 15
  unit: days
```

But it would come at the cost of repetition when the goal is to reverse several sequences.

Objections?
