### ISSUE TITLE
As a user, I want to be able to declare an instantaneous evaluation time_scale without it failing validation.

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#48]
Whether the data allows for such a `time_scale` is a different question, but, if the declaration includes an instantaneous `time_scale`, I shouldn't see this validation error:

    - ERROR: The evaluation 'time_scale' is prescriptive and cannot be instantaneous. Please remove the evaluation 'time_scale' or increase it and try again.

This occurred when a user posted a data-direct evaluation that looks like the YAML, below. I explained to her that you can't upscale to instantaneous, which is the smallest scale possible. James said in the dev call that it should be "acceptable" if the input data is instantaneous. It would essentially result in no upscaling, I think.

There is no WRES User Support ticket for this; rather, it was reported by email and the issue has already been explained to the reporter.

Thanks,

Hank

=================================

```yml
label: HEFS Evaluations RSA
observed:
  label: USGS Streamflow Observations
  sources:
  - interface: usgs nwis
    uri: https://nwis.waterservices.usgs.gov/nwis/iv
  variable:
    name: '00060'
  feature_authority: nws lid
  type: observations
predicted:
  label: HEFS RSA Forecast Test
  variable:
    name: QINE
  feature_authority: nws lid
  type: ensemble forecasts
features:
  - {observed: '11335000', predicted: MHBC1}
reference_dates:
  minimum: 2022-12-01T11:00:00Z
  maximum: 2023-03-31T12:00:00Z
valid_dates:
  minimum: 2022-12-01T11:00:00Z
  maximum: 2023-04-09T12:00:00Z
reference_date_pools:
  period: 1
  frequency: 1
  unit: days
lead_times:
  minimum: 96
  maximum: 144
  unit: hours
time_scale:
  period: 1
  unit: seconds
rescale_lenience: observed
values:
  minimum: 0.0
probability_thresholds: 
  values: [0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95]
  operator: greater
  apply_to: observed
metrics:
  - name: sample size
  - name: mean error
  - name: box plot of errors
  - name: mean square error
  - name: brier skill score
ensemble_average: mean
duration_format: days
output_formats:
  - format: csv2
  - format: pairs
  - format: png
```
