### ISSUE TITLE
Questions while using WRES for long term RFC hindcast evaluation

### ISSUE THREAD

**Issue by gabelewis2004** [NOAA-OWP/wres#491]
Hello,
I'm trying to use WRES to evaluate the skill of ensemble hindcast performance at several locations across numerous years. Thanks to the helpful declaration examples and github, we've been able to make substantial progress. However, I have a few questions that hopefully you all can help answer, sorry if they're silly questions that have been answered elsewhere.

1. We're trying to evaluate two sets of daily hindcast runs (old vs. new model parameters) for water years 1990-2023, which is over 12,000 files each. The only way I can get WRES to run is by pointing to a ~1 GB tgz file (of all 12,418 daily files) using:
`sources: /input/SRWC1/CW3E_HEFS_WRES_format/SRWC1.HEFS.tgz`
This .tgz file takes ~8 minutes to extract to ~16 GB, each time we run WRES. Is there any way to point to a folder of individual .csv files (e.g. sources: /input/.../*.csv)? Or to point to a file listing the source .csv files? With so many files I can't include each of them in the declaration .yml file. 
It looks like I could do something similar to this for one year? How can we easily modify it for an Oct-Oct water year or for specific time periods?
 ```
sources:
  - uri: /input/SRWC1/CW3E_HEFS_WRES_format/
    pattern: '**2017**.csv'
```

2. Of the 12,418 days, there are 419 that we want to exclude from our analysis (due to missing GEFS forcing data). We've been limiting the start and end dates of our analysis using the following code, but are wondering if we can explicitly omit specific days within that window.
```
valid_dates:
  minimum: 1989-10-01T00:00:00Z
  maximum: 2023-09-30T23:00:00Z
```

3. I'm having all sorts of issues trying to get the time zones correct, and the only way I can get WRES to evaluate pairs is with the following declaration (here I'm limiting the data to just WY2017 for simplicity). I don't think that I'm doing it correctly, but cannot figure out how to align the time zones properly without running into errors. I've tried messing with the time_shift, the time of the observed and ensemble data, as well as the time_zone_offset, but keep running into issues.

My observed dataset contains midnight-midnight PST daily values, and the observed data file begins with:
```
value_date,location,variable_name,measurement_unit,value
1912-03-01T06:00:00Z,SRWC1,QME,CFSD,39
1912-03-02T06:00:00Z,SRWC1,QME,CFSD,44
1912-03-03T06:00:00Z,SRWC1,QME,CFSD,44
```

In the declaration I am using a time_shift of 16 hours forward (WRES does not evaluate any pairs if I have a period: -8, despite that issue seemingly fixed a few years ago) for the observed discharge. I do not have a time_zone_offset.
```
  time_shift: 
    period: 16
    unit: hours
```

My ensemble data contains hourly GMT discharge. Each day's hindcast output begins similar to: ```
start_date,value_date,location,variable_name,measurement_unit,ensemble_name,ensemblemember_id,value
```
2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
...
2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
```

Below is my entire declaration file in case that helps pinpoint the issue. Thank you in advance for helping!

```
observed:
  #Observed flows are from 1912-03-01T12:00:00Z to 2024-12-31T12:00:00Z in "PST mid to mid," which is UTC -8
  sources: /input/SRWC1/SRWC1.QME.csv
  variable: QME
  type: observations
  #time_zone_offset: '-0600'
  time_scale:
    function: mean
    period: 24
    unit: hours
  time_shift: 
    period: 16
    unit: hours

predicted:
  #CW3E hindcasts from 10/1/2016 to 9/30/2017 in GMT 
  sources: /input/SRWC1/CW3E_HEFS_WRES_format/SRWC1.HEFS.WY2017.tgz
  variable: QINE
  type: ensemble forecasts
  time_scale:
    function: mean
    period: 1
    unit: hours
#  time_shift: 
#    period: 2
#    unit: hours

valid_dates:
  minimum: 2016-10-01T00:00:00Z
  maximum: 2017-09-30T23:00:00Z
features:
  - {observed: SRWC1, predicted: SRWC1}
unit: CFS

time_scale:
  function: mean
  period: 24
  unit: hours
duration_format: days
lead_times:
  minimum: 0
  maximum: 360
  unit: hours
lead_time_pools:
  period: 24
  frequency: 24
  unit: hours

probability_thresholds:
  values: [0.1,0.5,0.8,0.9,0.95,0.99,0.995]
  operator: greater equal
minimum_sample_size: 1
metrics:
  - sample size
  - mean error
  - mean absolute error
  - root mean square error
  - pearson correlation coefficient
  - bias fraction
  - brier score
  - continuous ranked probability score
  - relative operating characteristic score
  - brier skill score
  - mean square error skill score
 # - continuous ranked probability skill score
  - reliability diagram
#  - relative operating characteristic diagram
  - quantile quantile diagram
 # - name: rank histogram
 #   probability_thresholds:
 #     values: [0.1,0.5,0.8,0.9,0.95,0.99,0.995]
 #     apply_to: predicted
decimal_format: '#0.00000'
output_formats:
  - csv2
  - pairs
  - png
  - csv
```

**Comment by james-d-brown** [comment]
Hello Gabe,

Thanks for using WRES :) I'll address each issue in a separate post.

```
Is there any way to point to a folder of individual .csv files (e.g. sources: /input/.../*.csv)?
```

Yes, you simply point to the folder. For example:

```
observed: foo/observations
predicted: foo/predictions
```

Where `foo/observations` and `foo/predictions` may contain one or many files. The WRES will attempt to read all of the files within these subdirectories in this example.

If you want to specifically filter for file extensions, then you can use the `pattern`, like so:

```
observed: foo/observations
predicted:
   sources:
     - uri: foo/predictions
       pattern: '**/*.csv'
```

The pattern is a file `glob`, which is explained here:

https://en.wikipedia.org/wiki/Glob_(programming)

However, I looks like we need to do a better job of documenting this. Apparently, it isn't explained in our declaration language wiki. Apologies for that. The above will filter the `foo/predictions` subdirectory for any files that end with a csv extension. Note that the `**/` is important here.

```
How can we easily modify it for an Oct-Oct water year or for specific time periods?
```

The `pattern` filter is a gross filter on the files to consider and isn't really intended to filter the data on specific attributes, like time. Fundamentally, you can only use a file glob to filter in a way that is consistent with files/file names. In general, data to filter may not align with discrete files or file names.

It would be cleaner to build a set of filters that are appropriate to each attribute you want to filter, so this is what we should aim for.

If it turns out that some things cannot be filtered with the current software, we would be happy to create tickets to add these filters. That said, if you need to use this as a workaround for missing features in the interim, hopefully it helps to clarify that this is a file glob. That said, I'm not really an expert in glob patterns - I know a few of the basic ones, but that's about it :) If you need additional assistance on this, I'm sure I can find someone with more knowledge :)

**Comment by james-d-brown** [comment]
```
Of the 12,418 days, there are 419 that we want to exclude from our analysis (due to missing GEFS forcing data). We've been limiting the start and end dates of our analysis using the following code, but are wondering if we can explicitly omit specific days within that window.
```

Good question. As of now, that isn't possible. We can certainly add a feature or features to support this. For example, we could expand the `valid_dates` to support a list of intervals, like this:

```
valid_dates:
  - minimum: 1989-10-01T00:00:00Z
    maximum: 2023-09-30T23:00:00Z
  - minimum: 2023-10-01T00:00:00Z
    maximum: 2025-05-10T00:00:00Z
``

Alternatively, or in addition to the above, we could add a new declaration option to omit specific datetimes. When the dates to omit are adjacent to each other, intervals would be more efficient, else a list of datetimes.

**Comment by james-d-brown** [comment]
> 3. I'm having all sorts of issues trying to get the time zones correct, and the only way I can get WRES to evaluate pairs is with the following declaration (here I'm limiting the data to just WY2017 for simplicity). I don't think that I'm doing it correctly, but cannot figure out how to align the time zones properly without running into errors. I've tried messing with the time_shift, the time of the observed and ensemble data, as well as the time_zone_offset, but keep running into issues.
> 
> My observed dataset contains midnight-midnight PST daily values, and the observed data file begins with:
> 
> ```
> value_date,location,variable_name,measurement_unit,value
> 1912-03-01T06:00:00Z,SRWC1,QME,CFSD,39
> 1912-03-02T06:00:00Z,SRWC1,QME,CFSD,44
> 1912-03-03T06:00:00Z,SRWC1,QME,CFSD,44
> ```
> 
> In the declaration I am using a time_shift of 16 hours forward (WRES does not evaluate any pairs if I have a period: -8, despite that issue seemingly fixed a few years ago) for the observed discharge. I do not have a time_zone_offset.
> 
> ```
>   time_shift: 
>     period: 16
>     unit: hours
> ```
> 
> My ensemble data contains hourly GMT discharge. Each day's hindcast output begins similar to: ``` start_date,value_date,location,variable_name,measurement_unit,ensemble_name,ensemblemember_id,value
> 
> ```
> 2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
> 2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
> ...
> 2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
> 2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
> ```

A good general rule is to declare the data in whatever time zone they are in and then to shift the data, if really necessary, so that you can form pairs. I think the problem arises when trying to vary more than one thing at once. Ideally, the time zone information is contained within the data source. When the time zone information is contained within the data source, there is no need to declare a `time_zone_offset`. This is only required when the data source is silent.

In your example, the time zone information is explicit. In other words, this:

```
1912-03-01T06:00:00Z
```

Is an ISO8601 datetime "instant". An instant just means that it is expressed in UTC or Z=Zulu time, hence the `Z` at the end of the datetime. I mention this because you say the above is midnight in PST, but it doesn't look like that to me. I think PST is 7 hours behind UTC(?)

Anyway, it looks like your forecasts are 6 hours ahead of your observations, right?

```
2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
```

The goal would be to form a daily accumulation from the predictions that ends at 6Z (according to your observations). Whether you need to shift your data to achieve this will depend on the data. In most cases, the WRES should work this out and form an accumulation/aggregation when an aggregation can be formed. However, if the data are not aligned in UTC (after shifting them from whatever times they are declared or supplied in), then a `time_shift` may be needed to bring them into line.

I have no idea why a 16 hour time shift would work in your case, given what I am seeing above.

Perhaps you could upload a small example of the observations and predictions so that I can take a closer look.

Thanks!

**Comment by gabelewis2004** [comment]
Fantastic, thanks for the quick reply James! So incredibly helpful.

1. This is exactly what we were hoping for, I'll play around with the `glob` formatting since each of our files include their date in their name. This should be perfect for what we're trying to do.

2. It would be helpful for us to have multiple `valid_dates`,  if possible. Your example would be ideal, then we could input a list of days to use and just skip the days without GEFS forecasts, something like the following code to skip Feb 2020 (which doesn't have GEFS forecasts). This syntax currently throws an error, as does separating it into two `valid_dates` declarations.
```
valid_dates:
  - minimum: 1989-10-01T00:00:00Z
    maximum: 2020-01-31T23:00:00Z
  - minimum: 2020-03-01T00:00:00Z
    maximum: 2025-05-10T00:00:00Z
```

3. Thanks for the clear explanations. I didn't realize the daily observations should indicate the **end** of that 24-hour period, not the middle. (I'm assuming the hourly observations/forecasts also denote the end of that hour's discharge values?). I had added `T06:00:00Z `to the observations file as an (incorrect) guess while trying to troubleshoot, but have since changed the observation file to the following to represent the fact that they are midnight-midnight PST observations. I'm no longer using `time_shift` nor `time_zone_offset`:

```
value_date,location,variable_name,measurement_unit,value
1912-03-01T16:00:00Z,SRWC1,QME,CFSD,39
1912-03-02T16:00:00Z,SRWC1,QME,CFSD,44
1912-03-03T16:00:00Z,SRWC1,QME,CFSD,44
...
```

My ensemble forecasts are hourly GMT values and likewise don't have any `time_shift` nor `time_zone_offset`, I did not change the files so they begin:
```
2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
2017-10-01T12:00:00Z,2017-10-01T12:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
...
2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1980,7.5
2017-10-01T12:00:00Z,2017-10-01T13:00:00Z,SRWC1,QINE,CFS,MEFP,1981,7.5
```

I believe now the observation and ensemble data are correct and in the proper time zones, at least WRES is able to run without error. Does this make sense to you? Thanks.

**Comment by james-d-brown** [comment]
> Fantastic, thanks for the quick reply James! So incredibly helpful.
> 
> 1. This is exactly what we were hoping for, I'll play around with the `glob` formatting since each of our files include their date in their name. This should be perfect for what we're trying to do.

Sounds good.

> 3. It would be helpful for us to have multiple `valid_dates`,  if possible. Your example would be ideal, then we could input a list of days to use and just skip the days without GEFS forecasts, something like the following code to skip Feb 2020 (which doesn't have GEFS forecasts). This syntax currently throws an error, as does separating it into two `valid_dates` declarations.> 

Yeah, will need to add that feature. I will create a ticket for it.

> 3. Thanks for the clear explanations. I didn't realize the daily observations should indicate the **end** of that 24-hour period, not the middle. (I'm assuming the hourly observations/forecasts also denote the end of that hour's discharge values?). 

The time scale intervals within WRES are all considered to be half-open intervals that end at the designated time, i.e., the designated time is within the interval (at the end of) and the start instant is not within the interval. Any values that fall within the interval will form part of the upscaled value. The values must be distributed evenly within the interval, otherwise the WRES will not form an upscaled value and you will get an error along those lines. The WRES does not support downscaling. This also means that it does not support upscaling unless the values at the smaller scale overlap perfectly with the desired upscaled interval. For example, if you have 3-hourly accumulations, the WRES will not be able to form 8-hourly accumulations under any circumstances, because it won't know how to distribute the accumulation over the partial interval (3+3+2). That is also a downscaling problem.

> 7. I had added `T06:00:00Z `to the observations file as an (incorrect) guess while trying to troubleshoot, but have since changed the observation file to the following to represent the fact that they are midnight-midnight PST observations. I'm no longer using `time_shift` nor `time_zone_offset`:

Yeah, it is good general practice to declare the data exactly as they are in reality (ideally within the format itself and in UTC, which is what the CSV format does) and then, if the pairs cannot be formed, to use the `time_shift` parameter on only one side of the data. Vary one thing at once, basically. The `time_zone_offset` is simply to declare what the data is when the data doesn't specify itself.

> I believe now the observation and ensemble data are correct and in the proper time zones, at least WRES is able to run without error. Does this make sense to you?

The first part does, at least. However, I am not sure how the WRES can form a 24-hour mean ending at 16Z (observed) when the forecasts are issued at 12Z, unless the forecast valid times are such that they align with 16Z. By my calculation, this would only be the case if the forecast valid times were hourly or 2-hourly or 4-hourly, because all of those would be able to form a daily average ending at 16Z. It *looks* like your data is hourly(?). However, if it has hourly valid times, I really have no idea why you didn't get pairs in all circumstances before because a time shift (via the time zone or data specification or time shift) of *any* amount on an hourly cadence should still produce pairs, even if they are incorrect pairs. In many ways, hourly data is the trickiest because it is much easier to align things, which means it is much easier to align things incorrectly if something is declared incorrectly. Does that make sense?

In short, something doesn't fully add up, although I definitely think you're heading in the right direction. I would be happy to take a look at a sample of data if you want.

**Comment by gabelewis2004** [comment]
Thanks James.
I look forward to the multiple valid_dates option, I appreciate you working on that.

I've uploaded our observations and an example HEFS hindcast file to [this folder](https://drive.google.com/drive/folders/1D-mcMzp3gV7-Zk-VR1mKP0kvO4HZhOtS?usp=sharing), along with our validation declaration. You're correct that our hindcasts are hourly forecast values, so WRES should be able to form a 24-hour mean ending at 16Z (at least for anything beyond the first 4 hours). Please let me know if this makes sense, I think we're doing it correctly now, but I could definitely be mistaken. It's possible that last week I was (incorrectly) applying too many time shifts and causing errors, but things seem to be working properly now.
Thanks for all the help!
Gabe

**Comment by james-d-brown** [comment]
Yeah, I am pretty certain you have it correct now, I just don't understand why you were getting errors before rather than (incorrect) pairs. Unless they were validation errors of some kind. Do you recall what the errors were saying? If it was something about being unable to form any valid pairs, then that is the sort of error I would be surprised about. If it was an earlier validation error of some sort, then that could make sense, depending on what combination of things had been declared. I will take a look at the data, though.

**Comment by james-d-brown** [comment]
For example, if you were setting the time zone to something other than UTC in the declaration, then that should produce a validation error because the declaration (not UTC) would be in conflict with the data (UTC) and that would be an expected/correct validation error. If that was it, then there is probably nothing to investigate.

**Comment by james-d-brown** [comment]
I had a quick look at your declaration and data and it looks right to me. You could perhaps declare the `predicted` data as having an "instantaneous" `time_scale`, because it is likely instantaneous. However, this makes no practical difference in your case - the average over 24 hours will still be formed over the 24 values that fall within the averaging period (lower bound exclusive, upper bound inclusive). If you wanted to declare "instantaneous", there is no strict definition of this, but the WRES treats it as anything with a `time_scale` `period` of 1 minute or less, so something like this:

```
  time_scale:
    function: mean
    period: 1
    unit: seconds
```

It would merely serve as a clarifying gesture. In situations when you are not upscaling, it actually has some value in generating labels etc. for plots that are qualified as "instantaneous", but not in this case, because you are upscaling to a daily average (observation), so the plots are labelled accordingly.
