### ISSUE TITLE
As a user, when using fuzzy cross pairing, I expect the number of pairs using 3 hour lead time pools to match those using 6 hour lead time pools.

### ISSUE THREAD

**Issue by HankHerr-NOAA** [NOAA-OWP/wres#500]
For the evaluation below, the number of pairs when using a single 6-hour lead time pool far exceeds the total number of pairs when using 2 x 3-hour lead time pools. Per a comment from James, this is not desirable and merits a ticket. However, it may not be readily fixable.

See VLab ticket 146476. The issue arises because the `baseline` WRDS RFC forecasts use off-synoptic issued times, while the `predicted` NWM MRF forecast use synoptic reference times. Furthermore, the forecasts are hourly in both cases. Since the RFC issued time can be more than an hour off from the fuzzy cross-paired NWM forecast reference time (typically 2-3 hours, in fact), that leads to a situation where the baseline pair is in a different lead time pool than the predicted pair. In that situation, the cross-pair is dropped from the evaluation. 

Here are the JSON responses from WRDS for the observations, NWM MRF, and RFC forecasts:

`observed` - [hopc1_obs.json.gz](https://github.com/user-attachments/files/20519773/hopc1_obs.json.gz)
`predicted` - [hopc1_nwm_pred.json.gz](https://github.com/user-attachments/files/20519774/hopc1_nwm_pred.json.gz)
`baseline` - [hopc1_rfc_baseline.json.gz](https://github.com/user-attachments/files/20519772/hopc1_rfc_baseline.json.gz)

The declaration is below with WRDS URLs omitted. The feature has been fully specified. This produce a sample size image that shows the count for (0, 6] far exceeds that of (0, 3] and (3, 6] added together.

Thanks,

Hank

==========

```yaml
label: CNRFC - NWM vs RSA Recent
observed:
  label: WRDS Streamflow Obs
  sources:
    uri: https://WRDS/api/observed/v1.0/observed/streamflow
    interface: wrds obs
  variable: QR
  feature_authority: nws lid
  type: observations
predicted:
  label: NWM Streamflow Forecast
  sources:
    uri: https://WRDS/api/nwm3.0/v3.0/ops/medium_range
    interface: wrds nwm
  variable: streamflow
  type: single valued forecasts
baseline:
  label: AHPS Streamflow Forecast
  sources:
    uri: https://WRDS/api/rfc_forecast/v2.0/forecast/streamflow
    interface: wrds ahps
  variable: QR
  feature_authority: nws lid
  type: single valued forecasts
  separate_metrics: true
features:
- {observed: 'HOPC1', predicted: '8269119', baseline: 'HOPC1'}
unit: ft3/s
reference_dates:
  minimum: 2025-03-29T12:00:00Z
  maximum: 2025-05-28T12:00:00Z
valid_dates:
  minimum: 2025-03-29T12:00:00Z
  maximum: 2025-05-28T16:00:00Z
lead_times:
  minimum: 0
  maximum: 6
  unit: hours
time_pools:
  - lead_times:
      minimum: 0
      maximum: 3
      unit: hours
  - lead_times:
      minimum: 3
      maximum: 6
      unit: hours
  - lead_times:
      minimum: 0
      maximum: 6
      unit: hours
metrics:
  - pearson correlation coefficient
  - sample size
output_formats:
  - csv2
  - pairs
  - png
```
